// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: supervisor.proto

package supervisorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupervisorExecRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       string                    `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string                  `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Workdir       string                    `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Env           map[string]string         `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits        *SupervisorResourceLimits `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorExecRequest) Reset() {
	*x = SupervisorExecRequest{}
	mi := &file_supervisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorExecRequest) ProtoMessage() {}

func (x *SupervisorExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorExecRequest.ProtoReflect.Descriptor instead.
func (*SupervisorExecRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{0}
}

func (x *SupervisorExecRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SupervisorExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SupervisorExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SupervisorExecRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *SupervisorExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SupervisorExecRequest) GetLimits() *SupervisorResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type SupervisorResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores int32                  `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorResourceLimits) Reset() {
	*x = SupervisorResourceLimits{}
	mi := &file_supervisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorResourceLimits) ProtoMessage() {}

func (x *SupervisorResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorResourceLimits.ProtoReflect.Descriptor instead.
func (*SupervisorResourceLimits) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{1}
}

func (x *SupervisorResourceLimits) GetCpuMillicores() int32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *SupervisorResourceLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type SupervisorExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorExecResponse) Reset() {
	*x = SupervisorExecResponse{}
	mi := &file_supervisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorExecResponse) ProtoMessage() {}

func (x *SupervisorExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorExecResponse.ProtoReflect.Descriptor instead.
func (*SupervisorExecResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{2}
}

func (x *SupervisorExecResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SupervisorExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SupervisorExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SupervisorExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SupervisorExecResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SupervisorExecResponse) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type SupervisorParallelExecRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Commands      []*SupervisorExecRequest `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorParallelExecRequest) Reset() {
	*x = SupervisorParallelExecRequest{}
	mi := &file_supervisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorParallelExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorParallelExecRequest) ProtoMessage() {}

func (x *SupervisorParallelExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorParallelExecRequest.ProtoReflect.Descriptor instead.
func (*SupervisorParallelExecRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{3}
}

func (x *SupervisorParallelExecRequest) GetCommands() []*SupervisorExecRequest {
	if x != nil {
		return x.Commands
	}
	return nil
}

type SupervisorParallelExecResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*SupervisorExecResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorParallelExecResponse) Reset() {
	*x = SupervisorParallelExecResponse{}
	mi := &file_supervisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorParallelExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorParallelExecResponse) ProtoMessage() {}

func (x *SupervisorParallelExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorParallelExecResponse.ProtoReflect.Descriptor instead.
func (*SupervisorParallelExecResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{4}
}

func (x *SupervisorParallelExecResponse) GetResults() []*SupervisorExecResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type StreamOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // Optional: specific command in parallel batch.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputRequest) Reset() {
	*x = StreamOutputRequest{}
	mi := &file_supervisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputRequest) ProtoMessage() {}

func (x *StreamOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamOutputRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{5}
}

func (x *StreamOutputRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *StreamOutputRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type SupervisorOutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	IsStderr      bool                   `protobuf:"varint,2,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorOutputChunk) Reset() {
	*x = SupervisorOutputChunk{}
	mi := &file_supervisor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorOutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorOutputChunk) ProtoMessage() {}

func (x *SupervisorOutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorOutputChunk.ProtoReflect.Descriptor instead.
func (*SupervisorOutputChunk) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{6}
}

func (x *SupervisorOutputChunk) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SupervisorOutputChunk) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

func (x *SupervisorOutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SupervisorCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`          // Cancel entire execution.
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // Optional: cancel specific command.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorCancelRequest) Reset() {
	*x = SupervisorCancelRequest{}
	mi := &file_supervisor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorCancelRequest) ProtoMessage() {}

func (x *SupervisorCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorCancelRequest.ProtoReflect.Descriptor instead.
func (*SupervisorCancelRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{7}
}

func (x *SupervisorCancelRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *SupervisorCancelRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type SupervisorCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorCancelResponse) Reset() {
	*x = SupervisorCancelResponse{}
	mi := &file_supervisor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorCancelResponse) ProtoMessage() {}

func (x *SupervisorCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorCancelResponse.ProtoReflect.Descriptor instead.
func (*SupervisorCancelResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{8}
}

func (x *SupervisorCancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SupervisorCancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped"
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_supervisor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessInfo) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ProcessInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_supervisor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessList) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type SupervisorSetModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // "explore", "execute", "ask"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorSetModeRequest) Reset() {
	*x = SupervisorSetModeRequest{}
	mi := &file_supervisor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorSetModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorSetModeRequest) ProtoMessage() {}

func (x *SupervisorSetModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorSetModeRequest.ProtoReflect.Descriptor instead.
func (*SupervisorSetModeRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{11}
}

func (x *SupervisorSetModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SupervisorSetModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupervisorSetModeResponse) Reset() {
	*x = SupervisorSetModeResponse{}
	mi := &file_supervisor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisorSetModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisorSetModeResponse) ProtoMessage() {}

func (x *SupervisorSetModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisorSetModeResponse.ProtoReflect.Descriptor instead.
func (*SupervisorSetModeResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{12}
}

func (x *SupervisorSetModeResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SupervisorSetModeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_supervisor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{13}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_supervisor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{14}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_supervisor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{15}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_supervisor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{16}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_supervisor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{17}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_supervisor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supervisor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_supervisor_proto_rawDescGZIP(), []int{18}
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_supervisor_proto protoreflect.FileDescriptor

const file_supervisor_proto_rawDesc = "" +
	"\n" +
	"\x10supervisor.proto\x12\x12loka.supervisor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb3\x02\n" +
	"\x15SupervisorExecRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x12D\n" +
	"\x03env\x18\x05 \x03(\v22.loka.supervisor.v1.SupervisorExecRequest.EnvEntryR\x03env\x12D\n" +
	"\x06limits\x18\x06 \x01(\v2,.loka.supervisor.v1.SupervisorResourceLimitsR\x06limits\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x18SupervisorResourceLimits\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x05R\rcpuMillicores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"\xe7\x01\n" +
	"\x16SupervisorExecResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"f\n" +
	"\x1dSupervisorParallelExecRequest\x12E\n" +
	"\bcommands\x18\x01 \x03(\v2).loka.supervisor.v1.SupervisorExecRequestR\bcommands\"f\n" +
	"\x1eSupervisorParallelExecResponse\x12D\n" +
	"\aresults\x18\x01 \x03(\v2*.loka.supervisor.v1.SupervisorExecResponseR\aresults\"M\n" +
	"\x13StreamOutputRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\"g\n" +
	"\x15SupervisorOutputChunk\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tis_stderr\x18\x02 \x01(\bR\bisStderr\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"Q\n" +
	"\x17SupervisorCancelRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\"N\n" +
	"\x18SupervisorCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\vProcessInfo\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"L\n" +
	"\vProcessList\x12=\n" +
	"\tprocesses\x18\x01 \x03(\v2\x1f.loka.supervisor.v1.ProcessInfoR\tprocesses\".\n" +
	"\x18SupervisorSetModeRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"I\n" +
	"\x19SupervisorSetModeResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"@\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"I\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"I\n" +
	"\x0fListDirResponse\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.loka.supervisor.v1.DirEntryR\aentries2\xe2\x06\n" +
	"\x11SupervisorService\x12`\n" +
	"\aExecute\x12).loka.supervisor.v1.SupervisorExecRequest\x1a*.loka.supervisor.v1.SupervisorExecResponse\x12x\n" +
	"\x0fExecuteParallel\x121.loka.supervisor.v1.SupervisorParallelExecRequest\x1a2.loka.supervisor.v1.SupervisorParallelExecResponse\x12d\n" +
	"\fStreamOutput\x12'.loka.supervisor.v1.StreamOutputRequest\x1a).loka.supervisor.v1.SupervisorOutputChunk0\x01\x12c\n" +
	"\x06Cancel\x12+.loka.supervisor.v1.SupervisorCancelRequest\x1a,.loka.supervisor.v1.SupervisorCancelResponse\x12H\n" +
	"\rListProcesses\x12\x16.google.protobuf.Empty\x1a\x1f.loka.supervisor.v1.ProcessList\x12f\n" +
	"\aSetMode\x12,.loka.supervisor.v1.SupervisorSetModeRequest\x1a-.loka.supervisor.v1.SupervisorSetModeResponse\x12U\n" +
	"\bReadFile\x12#.loka.supervisor.v1.ReadFileRequest\x1a$.loka.supervisor.v1.ReadFileResponse\x12I\n" +
	"\tWriteFile\x12$.loka.supervisor.v1.WriteFileRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\aListDir\x12\".loka.supervisor.v1.ListDirRequest\x1a#.loka.supervisor.v1.ListDirResponseB)Z'github.com/vyprai/loka/api/supervisorv1b\x06proto3"

var (
	file_supervisor_proto_rawDescOnce sync.Once
	file_supervisor_proto_rawDescData []byte
)

func file_supervisor_proto_rawDescGZIP() []byte {
	file_supervisor_proto_rawDescOnce.Do(func() {
		file_supervisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supervisor_proto_rawDesc), len(file_supervisor_proto_rawDesc)))
	})
	return file_supervisor_proto_rawDescData
}

var file_supervisor_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_supervisor_proto_goTypes = []any{
	(*SupervisorExecRequest)(nil),          // 0: loka.supervisor.v1.SupervisorExecRequest
	(*SupervisorResourceLimits)(nil),       // 1: loka.supervisor.v1.SupervisorResourceLimits
	(*SupervisorExecResponse)(nil),         // 2: loka.supervisor.v1.SupervisorExecResponse
	(*SupervisorParallelExecRequest)(nil),  // 3: loka.supervisor.v1.SupervisorParallelExecRequest
	(*SupervisorParallelExecResponse)(nil), // 4: loka.supervisor.v1.SupervisorParallelExecResponse
	(*StreamOutputRequest)(nil),            // 5: loka.supervisor.v1.StreamOutputRequest
	(*SupervisorOutputChunk)(nil),          // 6: loka.supervisor.v1.SupervisorOutputChunk
	(*SupervisorCancelRequest)(nil),        // 7: loka.supervisor.v1.SupervisorCancelRequest
	(*SupervisorCancelResponse)(nil),       // 8: loka.supervisor.v1.SupervisorCancelResponse
	(*ProcessInfo)(nil),                    // 9: loka.supervisor.v1.ProcessInfo
	(*ProcessList)(nil),                    // 10: loka.supervisor.v1.ProcessList
	(*SupervisorSetModeRequest)(nil),       // 11: loka.supervisor.v1.SupervisorSetModeRequest
	(*SupervisorSetModeResponse)(nil),      // 12: loka.supervisor.v1.SupervisorSetModeResponse
	(*ReadFileRequest)(nil),                // 13: loka.supervisor.v1.ReadFileRequest
	(*ReadFileResponse)(nil),               // 14: loka.supervisor.v1.ReadFileResponse
	(*WriteFileRequest)(nil),               // 15: loka.supervisor.v1.WriteFileRequest
	(*ListDirRequest)(nil),                 // 16: loka.supervisor.v1.ListDirRequest
	(*DirEntry)(nil),                       // 17: loka.supervisor.v1.DirEntry
	(*ListDirResponse)(nil),                // 18: loka.supervisor.v1.ListDirResponse
	nil,                                    // 19: loka.supervisor.v1.SupervisorExecRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),          // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 21: google.protobuf.Empty
}
var file_supervisor_proto_depIdxs = []int32{
	19, // 0: loka.supervisor.v1.SupervisorExecRequest.env:type_name -> loka.supervisor.v1.SupervisorExecRequest.EnvEntry
	1,  // 1: loka.supervisor.v1.SupervisorExecRequest.limits:type_name -> loka.supervisor.v1.SupervisorResourceLimits
	20, // 2: loka.supervisor.v1.SupervisorExecResponse.started_at:type_name -> google.protobuf.Timestamp
	20, // 3: loka.supervisor.v1.SupervisorExecResponse.ended_at:type_name -> google.protobuf.Timestamp
	0,  // 4: loka.supervisor.v1.SupervisorParallelExecRequest.commands:type_name -> loka.supervisor.v1.SupervisorExecRequest
	2,  // 5: loka.supervisor.v1.SupervisorParallelExecResponse.results:type_name -> loka.supervisor.v1.SupervisorExecResponse
	20, // 6: loka.supervisor.v1.ProcessInfo.started_at:type_name -> google.protobuf.Timestamp
	9,  // 7: loka.supervisor.v1.ProcessList.processes:type_name -> loka.supervisor.v1.ProcessInfo
	17, // 8: loka.supervisor.v1.ListDirResponse.entries:type_name -> loka.supervisor.v1.DirEntry
	0,  // 9: loka.supervisor.v1.SupervisorService.Execute:input_type -> loka.supervisor.v1.SupervisorExecRequest
	3,  // 10: loka.supervisor.v1.SupervisorService.ExecuteParallel:input_type -> loka.supervisor.v1.SupervisorParallelExecRequest
	5,  // 11: loka.supervisor.v1.SupervisorService.StreamOutput:input_type -> loka.supervisor.v1.StreamOutputRequest
	7,  // 12: loka.supervisor.v1.SupervisorService.Cancel:input_type -> loka.supervisor.v1.SupervisorCancelRequest
	21, // 13: loka.supervisor.v1.SupervisorService.ListProcesses:input_type -> google.protobuf.Empty
	11, // 14: loka.supervisor.v1.SupervisorService.SetMode:input_type -> loka.supervisor.v1.SupervisorSetModeRequest
	13, // 15: loka.supervisor.v1.SupervisorService.ReadFile:input_type -> loka.supervisor.v1.ReadFileRequest
	15, // 16: loka.supervisor.v1.SupervisorService.WriteFile:input_type -> loka.supervisor.v1.WriteFileRequest
	16, // 17: loka.supervisor.v1.SupervisorService.ListDir:input_type -> loka.supervisor.v1.ListDirRequest
	2,  // 18: loka.supervisor.v1.SupervisorService.Execute:output_type -> loka.supervisor.v1.SupervisorExecResponse
	4,  // 19: loka.supervisor.v1.SupervisorService.ExecuteParallel:output_type -> loka.supervisor.v1.SupervisorParallelExecResponse
	6,  // 20: loka.supervisor.v1.SupervisorService.StreamOutput:output_type -> loka.supervisor.v1.SupervisorOutputChunk
	8,  // 21: loka.supervisor.v1.SupervisorService.Cancel:output_type -> loka.supervisor.v1.SupervisorCancelResponse
	10, // 22: loka.supervisor.v1.SupervisorService.ListProcesses:output_type -> loka.supervisor.v1.ProcessList
	12, // 23: loka.supervisor.v1.SupervisorService.SetMode:output_type -> loka.supervisor.v1.SupervisorSetModeResponse
	14, // 24: loka.supervisor.v1.SupervisorService.ReadFile:output_type -> loka.supervisor.v1.ReadFileResponse
	21, // 25: loka.supervisor.v1.SupervisorService.WriteFile:output_type -> google.protobuf.Empty
	18, // 26: loka.supervisor.v1.SupervisorService.ListDir:output_type -> loka.supervisor.v1.ListDirResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_supervisor_proto_init() }
func file_supervisor_proto_init() {
	if File_supervisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supervisor_proto_rawDesc), len(file_supervisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_supervisor_proto_goTypes,
		DependencyIndexes: file_supervisor_proto_depIdxs,
		MessageInfos:      file_supervisor_proto_msgTypes,
	}.Build()
	File_supervisor_proto = out.File
	file_supervisor_proto_goTypes = nil
	file_supervisor_proto_depIdxs = nil
}
