// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: supervisor.proto

package supervisorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupervisorService_Execute_FullMethodName         = "/loka.supervisor.v1.SupervisorService/Execute"
	SupervisorService_ExecuteParallel_FullMethodName = "/loka.supervisor.v1.SupervisorService/ExecuteParallel"
	SupervisorService_StreamOutput_FullMethodName    = "/loka.supervisor.v1.SupervisorService/StreamOutput"
	SupervisorService_Cancel_FullMethodName          = "/loka.supervisor.v1.SupervisorService/Cancel"
	SupervisorService_ListProcesses_FullMethodName   = "/loka.supervisor.v1.SupervisorService/ListProcesses"
	SupervisorService_SetMode_FullMethodName         = "/loka.supervisor.v1.SupervisorService/SetMode"
	SupervisorService_ReadFile_FullMethodName        = "/loka.supervisor.v1.SupervisorService/ReadFile"
	SupervisorService_WriteFile_FullMethodName       = "/loka.supervisor.v1.SupervisorService/WriteFile"
	SupervisorService_ListDir_FullMethodName         = "/loka.supervisor.v1.SupervisorService/ListDir"
)

// SupervisorServiceClient is the client API for SupervisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SupervisorService runs inside the guest VM, listening on vsock.
// The worker agent (host side) communicates with it to execute commands.
type SupervisorServiceClient interface {
	// Execute runs a single command and returns the result.
	Execute(ctx context.Context, in *SupervisorExecRequest, opts ...grpc.CallOption) (*SupervisorExecResponse, error)
	// ExecuteParallel runs multiple commands concurrently and returns all results.
	ExecuteParallel(ctx context.Context, in *SupervisorParallelExecRequest, opts ...grpc.CallOption) (*SupervisorParallelExecResponse, error)
	// StreamOutput streams stdout/stderr for a running command.
	StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SupervisorOutputChunk], error)
	// Cancel cancels a running command or batch.
	Cancel(ctx context.Context, in *SupervisorCancelRequest, opts ...grpc.CallOption) (*SupervisorCancelResponse, error)
	// ListProcesses returns all currently running processes.
	ListProcesses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProcessList, error)
	// SetMode changes the execution mode enforcement inside the VM.
	SetMode(ctx context.Context, in *SupervisorSetModeRequest, opts ...grpc.CallOption) (*SupervisorSetModeResponse, error)
	// File operations
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
}

type supervisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupervisorServiceClient(cc grpc.ClientConnInterface) SupervisorServiceClient {
	return &supervisorServiceClient{cc}
}

func (c *supervisorServiceClient) Execute(ctx context.Context, in *SupervisorExecRequest, opts ...grpc.CallOption) (*SupervisorExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupervisorExecResponse)
	err := c.cc.Invoke(ctx, SupervisorService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) ExecuteParallel(ctx context.Context, in *SupervisorParallelExecRequest, opts ...grpc.CallOption) (*SupervisorParallelExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupervisorParallelExecResponse)
	err := c.cc.Invoke(ctx, SupervisorService_ExecuteParallel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SupervisorOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SupervisorService_ServiceDesc.Streams[0], SupervisorService_StreamOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamOutputRequest, SupervisorOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SupervisorService_StreamOutputClient = grpc.ServerStreamingClient[SupervisorOutputChunk]

func (c *supervisorServiceClient) Cancel(ctx context.Context, in *SupervisorCancelRequest, opts ...grpc.CallOption) (*SupervisorCancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupervisorCancelResponse)
	err := c.cc.Invoke(ctx, SupervisorService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) ListProcesses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ProcessList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessList)
	err := c.cc.Invoke(ctx, SupervisorService_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) SetMode(ctx context.Context, in *SupervisorSetModeRequest, opts ...grpc.CallOption) (*SupervisorSetModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupervisorSetModeResponse)
	err := c.cc.Invoke(ctx, SupervisorService_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SupervisorService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SupervisorService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, SupervisorService_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupervisorServiceServer is the server API for SupervisorService service.
// All implementations must embed UnimplementedSupervisorServiceServer
// for forward compatibility.
//
// SupervisorService runs inside the guest VM, listening on vsock.
// The worker agent (host side) communicates with it to execute commands.
type SupervisorServiceServer interface {
	// Execute runs a single command and returns the result.
	Execute(context.Context, *SupervisorExecRequest) (*SupervisorExecResponse, error)
	// ExecuteParallel runs multiple commands concurrently and returns all results.
	ExecuteParallel(context.Context, *SupervisorParallelExecRequest) (*SupervisorParallelExecResponse, error)
	// StreamOutput streams stdout/stderr for a running command.
	StreamOutput(*StreamOutputRequest, grpc.ServerStreamingServer[SupervisorOutputChunk]) error
	// Cancel cancels a running command or batch.
	Cancel(context.Context, *SupervisorCancelRequest) (*SupervisorCancelResponse, error)
	// ListProcesses returns all currently running processes.
	ListProcesses(context.Context, *emptypb.Empty) (*ProcessList, error)
	// SetMode changes the execution mode enforcement inside the VM.
	SetMode(context.Context, *SupervisorSetModeRequest) (*SupervisorSetModeResponse, error)
	// File operations
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*emptypb.Empty, error)
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	mustEmbedUnimplementedSupervisorServiceServer()
}

// UnimplementedSupervisorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupervisorServiceServer struct{}

func (UnimplementedSupervisorServiceServer) Execute(context.Context, *SupervisorExecRequest) (*SupervisorExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSupervisorServiceServer) ExecuteParallel(context.Context, *SupervisorParallelExecRequest) (*SupervisorParallelExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteParallel not implemented")
}
func (UnimplementedSupervisorServiceServer) StreamOutput(*StreamOutputRequest, grpc.ServerStreamingServer[SupervisorOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamOutput not implemented")
}
func (UnimplementedSupervisorServiceServer) Cancel(context.Context, *SupervisorCancelRequest) (*SupervisorCancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedSupervisorServiceServer) ListProcesses(context.Context, *emptypb.Empty) (*ProcessList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedSupervisorServiceServer) SetMode(context.Context, *SupervisorSetModeRequest) (*SupervisorSetModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedSupervisorServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSupervisorServiceServer) WriteFile(context.Context, *WriteFileRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSupervisorServiceServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedSupervisorServiceServer) mustEmbedUnimplementedSupervisorServiceServer() {}
func (UnimplementedSupervisorServiceServer) testEmbeddedByValue()                           {}

// UnsafeSupervisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupervisorServiceServer will
// result in compilation errors.
type UnsafeSupervisorServiceServer interface {
	mustEmbedUnimplementedSupervisorServiceServer()
}

func RegisterSupervisorServiceServer(s grpc.ServiceRegistrar, srv SupervisorServiceServer) {
	// If the following call panics, it indicates UnimplementedSupervisorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupervisorService_ServiceDesc, srv)
}

func _SupervisorService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupervisorExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).Execute(ctx, req.(*SupervisorExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_ExecuteParallel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupervisorParallelExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).ExecuteParallel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_ExecuteParallel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).ExecuteParallel(ctx, req.(*SupervisorParallelExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_StreamOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SupervisorServiceServer).StreamOutput(m, &grpc.GenericServerStream[StreamOutputRequest, SupervisorOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SupervisorService_StreamOutputServer = grpc.ServerStreamingServer[SupervisorOutputChunk]

func _SupervisorService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupervisorCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).Cancel(ctx, req.(*SupervisorCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).ListProcesses(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupervisorSetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).SetMode(ctx, req.(*SupervisorSetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupervisorService_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupervisorService_ServiceDesc is the grpc.ServiceDesc for SupervisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupervisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loka.supervisor.v1.SupervisorService",
	HandlerType: (*SupervisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SupervisorService_Execute_Handler,
		},
		{
			MethodName: "ExecuteParallel",
			Handler:    _SupervisorService_ExecuteParallel_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _SupervisorService_Cancel_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _SupervisorService_ListProcesses_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _SupervisorService_SetMode_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SupervisorService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SupervisorService_WriteFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _SupervisorService_ListDir_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOutput",
			Handler:       _SupervisorService_StreamOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "supervisor.proto",
}
