// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: control.proto

package lokav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_CreateSession_FullMethodName     = "/loka.api.v1.ControlService/CreateSession"
	ControlService_GetSession_FullMethodName        = "/loka.api.v1.ControlService/GetSession"
	ControlService_ListSessions_FullMethodName      = "/loka.api.v1.ControlService/ListSessions"
	ControlService_DestroySession_FullMethodName    = "/loka.api.v1.ControlService/DestroySession"
	ControlService_PauseSession_FullMethodName      = "/loka.api.v1.ControlService/PauseSession"
	ControlService_ResumeSession_FullMethodName     = "/loka.api.v1.ControlService/ResumeSession"
	ControlService_SetSessionMode_FullMethodName    = "/loka.api.v1.ControlService/SetSessionMode"
	ControlService_Exec_FullMethodName              = "/loka.api.v1.ControlService/Exec"
	ControlService_GetExecution_FullMethodName      = "/loka.api.v1.ControlService/GetExecution"
	ControlService_ListExecutions_FullMethodName    = "/loka.api.v1.ControlService/ListExecutions"
	ControlService_CancelExecution_FullMethodName   = "/loka.api.v1.ControlService/CancelExecution"
	ControlService_StreamExecOutput_FullMethodName  = "/loka.api.v1.ControlService/StreamExecOutput"
	ControlService_CreateCheckpoint_FullMethodName  = "/loka.api.v1.ControlService/CreateCheckpoint"
	ControlService_GetCheckpoint_FullMethodName     = "/loka.api.v1.ControlService/GetCheckpoint"
	ControlService_ListCheckpoints_FullMethodName   = "/loka.api.v1.ControlService/ListCheckpoints"
	ControlService_RestoreCheckpoint_FullMethodName = "/loka.api.v1.ControlService/RestoreCheckpoint"
	ControlService_DeleteCheckpoint_FullMethodName  = "/loka.api.v1.ControlService/DeleteCheckpoint"
	ControlService_InstallPackage_FullMethodName    = "/loka.api.v1.ControlService/InstallPackage"
	ControlService_ListPackages_FullMethodName      = "/loka.api.v1.ControlService/ListPackages"
	ControlService_ValidatePackages_FullMethodName  = "/loka.api.v1.ControlService/ValidatePackages"
	ControlService_CreateProfile_FullMethodName     = "/loka.api.v1.ControlService/CreateProfile"
	ControlService_GetProfile_FullMethodName        = "/loka.api.v1.ControlService/GetProfile"
	ControlService_ListProfiles_FullMethodName      = "/loka.api.v1.ControlService/ListProfiles"
	ControlService_UpdateProfile_FullMethodName     = "/loka.api.v1.ControlService/UpdateProfile"
	ControlService_DeleteProfile_FullMethodName     = "/loka.api.v1.ControlService/DeleteProfile"
	ControlService_ListWorkers_FullMethodName       = "/loka.api.v1.ControlService/ListWorkers"
	ControlService_GetWorker_FullMethodName         = "/loka.api.v1.ControlService/GetWorker"
	ControlService_DrainWorker_FullMethodName       = "/loka.api.v1.ControlService/DrainWorker"
	ControlService_RemoveWorker_FullMethodName      = "/loka.api.v1.ControlService/RemoveWorker"
	ControlService_FileTunnel_FullMethodName        = "/loka.api.v1.ControlService/FileTunnel"
	ControlService_PortForward_FullMethodName       = "/loka.api.v1.ControlService/PortForward"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlService is the public API exposed by the LOKA control plane.
// Used by external clients (agent systems, lokactl CLI).
type ControlServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PauseSession(ctx context.Context, in *PauseSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*Session, error)
	SetSessionMode(ctx context.Context, in *SetSessionModeRequest, opts ...grpc.CallOption) (*Session, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*Execution, error)
	GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*Execution, error)
	ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error)
	CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*Execution, error)
	StreamExecOutput(ctx context.Context, in *StreamExecOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error)
	CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*Checkpoint, error)
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*Checkpoint, error)
	ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*CheckpointDAG, error)
	RestoreCheckpoint(ctx context.Context, in *RestoreCheckpointRequest, opts ...grpc.CallOption) (*Session, error)
	DeleteCheckpoint(ctx context.Context, in *DeleteCheckpointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	InstallPackage(ctx context.Context, in *InstallPackageRequest, opts ...grpc.CallOption) (*Package, error)
	ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error)
	ValidatePackages(ctx context.Context, in *ValidatePackagesRequest, opts ...grpc.CallOption) (*ValidatePackagesResponse, error)
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*PackageProfile, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*PackageProfile, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*PackageProfile, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	GetWorker(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*Worker, error)
	DrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*Worker, error)
	RemoveWorker(ctx context.Context, in *RemoveWorkerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ─── File Tunnel ─────────────────────────────────────────
	// Bidirectional stream for mounting local files into a session.
	FileTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileTunnelMessage, FileTunnelMessage], error)
	// ─── Port Forward ────────────────────────────────────────
	// Bidirectional stream for tunneling TCP connections to a session VM.
	PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PortForwardMessage, PortForwardMessage], error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, ControlService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, ControlService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlService_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) PauseSession(ctx context.Context, in *PauseSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, ControlService_PauseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, ControlService_ResumeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetSessionMode(ctx context.Context, in *SetSessionModeRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, ControlService_SetSessionMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*Execution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Execution)
	err := c.cc.Invoke(ctx, ControlService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*Execution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Execution)
	err := c.cc.Invoke(ctx, ControlService_GetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*Execution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Execution)
	err := c.cc.Invoke(ctx, ControlService_CancelExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) StreamExecOutput(ctx context.Context, in *StreamExecOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_StreamExecOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamExecOutputRequest, OutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_StreamExecOutputClient = grpc.ServerStreamingClient[OutputChunk]

func (c *controlServiceClient) CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*Checkpoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Checkpoint)
	err := c.cc.Invoke(ctx, ControlService_CreateCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*Checkpoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Checkpoint)
	err := c.cc.Invoke(ctx, ControlService_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*CheckpointDAG, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointDAG)
	err := c.cc.Invoke(ctx, ControlService_ListCheckpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RestoreCheckpoint(ctx context.Context, in *RestoreCheckpointRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, ControlService_RestoreCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DeleteCheckpoint(ctx context.Context, in *DeleteCheckpointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlService_DeleteCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) InstallPackage(ctx context.Context, in *InstallPackageRequest, opts ...grpc.CallOption) (*Package, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Package)
	err := c.cc.Invoke(ctx, ControlService_InstallPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPackagesResponse)
	err := c.cc.Invoke(ctx, ControlService_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ValidatePackages(ctx context.Context, in *ValidatePackagesRequest, opts ...grpc.CallOption) (*ValidatePackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePackagesResponse)
	err := c.cc.Invoke(ctx, ControlService_ValidatePackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*PackageProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageProfile)
	err := c.cc.Invoke(ctx, ControlService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*PackageProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageProfile)
	err := c.cc.Invoke(ctx, ControlService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, ControlService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*PackageProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageProfile)
	err := c.cc.Invoke(ctx, ControlService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, ControlService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetWorker(ctx context.Context, in *GetWorkerRequest, opts ...grpc.CallOption) (*Worker, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Worker)
	err := c.cc.Invoke(ctx, ControlService_GetWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*Worker, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Worker)
	err := c.cc.Invoke(ctx, ControlService_DrainWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RemoveWorker(ctx context.Context, in *RemoveWorkerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlService_RemoveWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) FileTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FileTunnelMessage, FileTunnelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[1], ControlService_FileTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileTunnelMessage, FileTunnelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_FileTunnelClient = grpc.BidiStreamingClient[FileTunnelMessage, FileTunnelMessage]

func (c *controlServiceClient) PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PortForwardMessage, PortForwardMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[2], ControlService_PortForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortForwardMessage, PortForwardMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_PortForwardClient = grpc.BidiStreamingClient[PortForwardMessage, PortForwardMessage]

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
//
// ControlService is the public API exposed by the LOKA control plane.
// Used by external clients (agent systems, lokactl CLI).
type ControlServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DestroySession(context.Context, *DestroySessionRequest) (*emptypb.Empty, error)
	PauseSession(context.Context, *PauseSessionRequest) (*Session, error)
	ResumeSession(context.Context, *ResumeSessionRequest) (*Session, error)
	SetSessionMode(context.Context, *SetSessionModeRequest) (*Session, error)
	Exec(context.Context, *ExecRequest) (*Execution, error)
	GetExecution(context.Context, *GetExecutionRequest) (*Execution, error)
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	CancelExecution(context.Context, *CancelExecutionRequest) (*Execution, error)
	StreamExecOutput(*StreamExecOutputRequest, grpc.ServerStreamingServer[OutputChunk]) error
	CreateCheckpoint(context.Context, *CreateCheckpointRequest) (*Checkpoint, error)
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*Checkpoint, error)
	ListCheckpoints(context.Context, *ListCheckpointsRequest) (*CheckpointDAG, error)
	RestoreCheckpoint(context.Context, *RestoreCheckpointRequest) (*Session, error)
	DeleteCheckpoint(context.Context, *DeleteCheckpointRequest) (*emptypb.Empty, error)
	InstallPackage(context.Context, *InstallPackageRequest) (*Package, error)
	ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error)
	ValidatePackages(context.Context, *ValidatePackagesRequest) (*ValidatePackagesResponse, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*PackageProfile, error)
	GetProfile(context.Context, *GetProfileRequest) (*PackageProfile, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*PackageProfile, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*emptypb.Empty, error)
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	GetWorker(context.Context, *GetWorkerRequest) (*Worker, error)
	DrainWorker(context.Context, *DrainWorkerRequest) (*Worker, error)
	RemoveWorker(context.Context, *RemoveWorkerRequest) (*emptypb.Empty, error)
	// ─── File Tunnel ─────────────────────────────────────────
	// Bidirectional stream for mounting local files into a session.
	FileTunnel(grpc.BidiStreamingServer[FileTunnelMessage, FileTunnelMessage]) error
	// ─── Port Forward ────────────────────────────────────────
	// Bidirectional stream for tunneling TCP connections to a session VM.
	PortForward(grpc.BidiStreamingServer[PortForwardMessage, PortForwardMessage]) error
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedControlServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedControlServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedControlServiceServer) DestroySession(context.Context, *DestroySessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedControlServiceServer) PauseSession(context.Context, *PauseSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseSession not implemented")
}
func (UnimplementedControlServiceServer) ResumeSession(context.Context, *ResumeSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSession not implemented")
}
func (UnimplementedControlServiceServer) SetSessionMode(context.Context, *SetSessionModeRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSessionMode not implemented")
}
func (UnimplementedControlServiceServer) Exec(context.Context, *ExecRequest) (*Execution, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedControlServiceServer) GetExecution(context.Context, *GetExecutionRequest) (*Execution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecution not implemented")
}
func (UnimplementedControlServiceServer) ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedControlServiceServer) CancelExecution(context.Context, *CancelExecutionRequest) (*Execution, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExecution not implemented")
}
func (UnimplementedControlServiceServer) StreamExecOutput(*StreamExecOutputRequest, grpc.ServerStreamingServer[OutputChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamExecOutput not implemented")
}
func (UnimplementedControlServiceServer) CreateCheckpoint(context.Context, *CreateCheckpointRequest) (*Checkpoint, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCheckpoint not implemented")
}
func (UnimplementedControlServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*Checkpoint, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedControlServiceServer) ListCheckpoints(context.Context, *ListCheckpointsRequest) (*CheckpointDAG, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCheckpoints not implemented")
}
func (UnimplementedControlServiceServer) RestoreCheckpoint(context.Context, *RestoreCheckpointRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreCheckpoint not implemented")
}
func (UnimplementedControlServiceServer) DeleteCheckpoint(context.Context, *DeleteCheckpointRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCheckpoint not implemented")
}
func (UnimplementedControlServiceServer) InstallPackage(context.Context, *InstallPackageRequest) (*Package, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPackage not implemented")
}
func (UnimplementedControlServiceServer) ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedControlServiceServer) ValidatePackages(context.Context, *ValidatePackagesRequest) (*ValidatePackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePackages not implemented")
}
func (UnimplementedControlServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*PackageProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedControlServiceServer) GetProfile(context.Context, *GetProfileRequest) (*PackageProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedControlServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedControlServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*PackageProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedControlServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedControlServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedControlServiceServer) GetWorker(context.Context, *GetWorkerRequest) (*Worker, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorker not implemented")
}
func (UnimplementedControlServiceServer) DrainWorker(context.Context, *DrainWorkerRequest) (*Worker, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainWorker not implemented")
}
func (UnimplementedControlServiceServer) RemoveWorker(context.Context, *RemoveWorkerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorker not implemented")
}
func (UnimplementedControlServiceServer) FileTunnel(grpc.BidiStreamingServer[FileTunnelMessage, FileTunnelMessage]) error {
	return status.Error(codes.Unimplemented, "method FileTunnel not implemented")
}
func (UnimplementedControlServiceServer) PortForward(grpc.BidiStreamingServer[PortForwardMessage, PortForwardMessage]) error {
	return status.Error(codes.Unimplemented, "method PortForward not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_PauseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).PauseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_PauseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).PauseSession(ctx, req.(*PauseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ResumeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ResumeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ResumeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ResumeSession(ctx, req.(*ResumeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetSessionMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSessionModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetSessionMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetSessionMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetSessionMode(ctx, req.(*SetSessionModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetExecution(ctx, req.(*GetExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListExecutions(ctx, req.(*ListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CancelExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CancelExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CancelExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CancelExecution(ctx, req.(*CancelExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_StreamExecOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamExecOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).StreamExecOutput(m, &grpc.GenericServerStream[StreamExecOutputRequest, OutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_StreamExecOutputServer = grpc.ServerStreamingServer[OutputChunk]

func _ControlService_CreateCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateCheckpoint(ctx, req.(*CreateCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListCheckpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCheckpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListCheckpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListCheckpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListCheckpoints(ctx, req.(*ListCheckpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RestoreCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RestoreCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RestoreCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RestoreCheckpoint(ctx, req.(*RestoreCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DeleteCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DeleteCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DeleteCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DeleteCheckpoint(ctx, req.(*DeleteCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_InstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).InstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_InstallPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).InstallPackage(ctx, req.(*InstallPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListPackages(ctx, req.(*ListPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ValidatePackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ValidatePackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ValidatePackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ValidatePackages(ctx, req.(*ValidatePackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetWorker(ctx, req.(*GetWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DrainWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DrainWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DrainWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DrainWorker(ctx, req.(*DrainWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RemoveWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RemoveWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RemoveWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RemoveWorker(ctx, req.(*RemoveWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_FileTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).FileTunnel(&grpc.GenericServerStream[FileTunnelMessage, FileTunnelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_FileTunnelServer = grpc.BidiStreamingServer[FileTunnelMessage, FileTunnelMessage]

func _ControlService_PortForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).PortForward(&grpc.GenericServerStream[PortForwardMessage, PortForwardMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_PortForwardServer = grpc.BidiStreamingServer[PortForwardMessage, PortForwardMessage]

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loka.api.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _ControlService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _ControlService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _ControlService_ListSessions_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _ControlService_DestroySession_Handler,
		},
		{
			MethodName: "PauseSession",
			Handler:    _ControlService_PauseSession_Handler,
		},
		{
			MethodName: "ResumeSession",
			Handler:    _ControlService_ResumeSession_Handler,
		},
		{
			MethodName: "SetSessionMode",
			Handler:    _ControlService_SetSessionMode_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _ControlService_Exec_Handler,
		},
		{
			MethodName: "GetExecution",
			Handler:    _ControlService_GetExecution_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _ControlService_ListExecutions_Handler,
		},
		{
			MethodName: "CancelExecution",
			Handler:    _ControlService_CancelExecution_Handler,
		},
		{
			MethodName: "CreateCheckpoint",
			Handler:    _ControlService_CreateCheckpoint_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _ControlService_GetCheckpoint_Handler,
		},
		{
			MethodName: "ListCheckpoints",
			Handler:    _ControlService_ListCheckpoints_Handler,
		},
		{
			MethodName: "RestoreCheckpoint",
			Handler:    _ControlService_RestoreCheckpoint_Handler,
		},
		{
			MethodName: "DeleteCheckpoint",
			Handler:    _ControlService_DeleteCheckpoint_Handler,
		},
		{
			MethodName: "InstallPackage",
			Handler:    _ControlService_InstallPackage_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _ControlService_ListPackages_Handler,
		},
		{
			MethodName: "ValidatePackages",
			Handler:    _ControlService_ValidatePackages_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _ControlService_CreateProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ControlService_GetProfile_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _ControlService_ListProfiles_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _ControlService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _ControlService_DeleteProfile_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _ControlService_ListWorkers_Handler,
		},
		{
			MethodName: "GetWorker",
			Handler:    _ControlService_GetWorker_Handler,
		},
		{
			MethodName: "DrainWorker",
			Handler:    _ControlService_DrainWorker_Handler,
		},
		{
			MethodName: "RemoveWorker",
			Handler:    _ControlService_RemoveWorker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExecOutput",
			Handler:       _ControlService_StreamExecOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileTunnel",
			Handler:       _ControlService_FileTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PortForward",
			Handler:       _ControlService_PortForward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "control.proto",
}
