// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: control.proto

package lokav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Snapshot      string                 `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Packages      []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Mode          ExecMode               `protobuf:"varint,5,opt,name=mode,proto3,enum=loka.api.v1.ExecMode" json:"mode,omitempty"`
	Vcpus         int32                  `protobuf:"varint,6,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,7,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkerLabels  map[string]string      `protobuf:"bytes,9,rep,name=worker_labels,json=workerLabels,proto3" json:"worker_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Scheduling affinity.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *CreateSessionRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CreateSessionRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CreateSessionRequest) GetMode() ExecMode {
	if x != nil {
		return x.Mode
	}
	return ExecMode_EXEC_MODE_UNSPECIFIED
}

func (x *CreateSessionRequest) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *CreateSessionRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateSessionRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateSessionRequest) GetWorkerLabels() map[string]string {
	if x != nil {
		return x.WorkerLabels
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SessionStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=loka.api.v1.SessionStatus" json:"status,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsRequest) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *ListSessionsRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *DestroySessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DestroySessionRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PauseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSessionRequest) Reset() {
	*x = PauseSessionRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSessionRequest) ProtoMessage() {}

func (x *PauseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSessionRequest.ProtoReflect.Descriptor instead.
func (*PauseSessionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *PauseSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSessionRequest) Reset() {
	*x = ResumeSessionRequest{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSessionRequest) ProtoMessage() {}

func (x *ResumeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSessionRequest.ProtoReflect.Descriptor instead.
func (*ResumeSessionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetSessionModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          ExecMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=loka.api.v1.ExecMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSessionModeRequest) Reset() {
	*x = SetSessionModeRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSessionModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSessionModeRequest) ProtoMessage() {}

func (x *SetSessionModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSessionModeRequest.ProtoReflect.Descriptor instead.
func (*SetSessionModeRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *SetSessionModeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetSessionModeRequest) GetMode() ExecMode {
	if x != nil {
		return x.Mode
	}
	return ExecMode_EXEC_MODE_UNSPECIFIED
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Commands      []*Command             `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Parallel      bool                   `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *ExecRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecRequest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ExecRequest) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *GetExecutionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetExecutionRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type ListExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        ExecStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=loka.api.v1.ExecStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsRequest) Reset() {
	*x = ListExecutionsRequest{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsRequest) ProtoMessage() {}

func (x *ListExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *ListExecutionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListExecutionsRequest) GetStatus() ExecStatus {
	if x != nil {
		return x.Status
	}
	return ExecStatus_EXEC_STATUS_UNSPECIFIED
}

func (x *ListExecutionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListExecutionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*Execution           `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *ListExecutionsResponse) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListExecutionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	CancelAll     bool                   `protobuf:"varint,3,opt,name=cancel_all,json=cancelAll,proto3" json:"cancel_all,omitempty"` // If true, cancel all running executions in the session.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *CancelExecutionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelExecutionRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *CancelExecutionRequest) GetCancelAll() bool {
	if x != nil {
		return x.CancelAll
	}
	return false
}

type StreamExecOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // Optional: stream a specific command's output.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExecOutputRequest) Reset() {
	*x = StreamExecOutputRequest{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecOutputRequest) ProtoMessage() {}

func (x *StreamExecOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamExecOutputRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *StreamExecOutputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamExecOutputRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *StreamExecOutputRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type OutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	IsStderr      bool                   `protobuf:"varint,2,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *OutputChunk) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *OutputChunk) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

func (x *OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          CheckpointType         `protobuf:"varint,2,opt,name=type,proto3,enum=loka.api.v1.CheckpointType" json:"type,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckpointRequest) Reset() {
	*x = CreateCheckpointRequest{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckpointRequest) ProtoMessage() {}

func (x *CreateCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckpointRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCheckpointRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateCheckpointRequest) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *CreateCheckpointRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointRequest) Reset() {
	*x = GetCheckpointRequest{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointRequest) ProtoMessage() {}

func (x *GetCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *GetCheckpointRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type ListCheckpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckpointsRequest) Reset() {
	*x = ListCheckpointsRequest{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckpointsRequest) ProtoMessage() {}

func (x *ListCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*ListCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *ListCheckpointsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RestoreCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCheckpointRequest) Reset() {
	*x = RestoreCheckpointRequest{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCheckpointRequest) ProtoMessage() {}

func (x *RestoreCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCheckpointRequest.ProtoReflect.Descriptor instead.
func (*RestoreCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *RestoreCheckpointRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RestoreCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type DeleteCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCheckpointRequest) Reset() {
	*x = DeleteCheckpointRequest{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCheckpointRequest) ProtoMessage() {}

func (x *DeleteCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCheckpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCheckpointRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type InstallPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageRequest) Reset() {
	*x = InstallPackageRequest{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageRequest) ProtoMessage() {}

func (x *InstallPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageRequest.ProtoReflect.Descriptor instead.
func (*InstallPackageRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *InstallPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesRequest) Reset() {
	*x = ListPackagesRequest{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesRequest) ProtoMessage() {}

func (x *ListPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListPackagesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

type ListPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*Package             `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesResponse) Reset() {
	*x = ListPackagesResponse{}
	mi := &file_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesResponse) ProtoMessage() {}

func (x *ListPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListPackagesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{22}
}

func (x *ListPackagesResponse) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

type ValidatePackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePackagesRequest) Reset() {
	*x = ValidatePackagesRequest{}
	mi := &file_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePackagesRequest) ProtoMessage() {}

func (x *ValidatePackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePackagesRequest.ProtoReflect.Descriptor instead.
func (*ValidatePackagesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{23}
}

func (x *ValidatePackagesRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type ValidatePackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]bool        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // package name -> available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePackagesResponse) Reset() {
	*x = ValidatePackagesResponse{}
	mi := &file_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePackagesResponse) ProtoMessage() {}

func (x *ValidatePackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePackagesResponse.ProtoReflect.Descriptor instead.
func (*ValidatePackagesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{24}
}

func (x *ValidatePackagesResponse) GetResults() map[string]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Packages      []string               `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{25}
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{26}
}

func (x *GetProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{27}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*PackageProfile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{28}
}

func (x *ListProfilesResponse) GetProfiles() []*PackageProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Add           []string               `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateProfileRequest) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Status        WorkerStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=loka.api.v1.WorkerStatus" json:"status,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{31}
}

func (x *ListWorkersRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListWorkersRequest) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_WORKER_STATUS_UNSPECIFIED
}

func (x *ListWorkersRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListWorkersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*Worker              `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{32}
}

func (x *ListWorkersResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *ListWorkersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerRequest) Reset() {
	*x = GetWorkerRequest{}
	mi := &file_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerRequest) ProtoMessage() {}

func (x *GetWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{33}
}

func (x *GetWorkerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DrainWorkerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DrainWorkerRequest) Reset() {
	*x = DrainWorkerRequest{}
	mi := &file_control_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainWorkerRequest) ProtoMessage() {}

func (x *DrainWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainWorkerRequest.ProtoReflect.Descriptor instead.
func (*DrainWorkerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{34}
}

func (x *DrainWorkerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DrainWorkerRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RemoveWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorkerRequest) Reset() {
	*x = RemoveWorkerRequest{}
	mi := &file_control_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkerRequest) ProtoMessage() {}

func (x *RemoveWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkerRequest.ProtoReflect.Descriptor instead.
func (*RemoveWorkerRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{35}
}

func (x *RemoveWorkerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveWorkerRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\vloka.api.v1\x1a\vtypes.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf7\x03\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bsnapshot\x18\x02 \x01(\tR\bsnapshot\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12)\n" +
	"\x04mode\x18\x05 \x01(\x0e2\x15.loka.api.v1.ExecModeR\x04mode\x12\x14\n" +
	"\x05vcpus\x18\x06 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\a \x01(\x05R\bmemoryMb\x12E\n" +
	"\x06labels\x18\b \x03(\v2-.loka.api.v1.CreateSessionRequest.LabelsEntryR\x06labels\x12X\n" +
	"\rworker_labels\x18\t \x03(\v23.loka.api.v1.CreateSessionRequest.WorkerLabelsEntryR\fworkerLabels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11WorkerLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x94\x01\n" +
	"\x13ListSessionsRequest\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.loka.api.v1.SessionStatusR\x06status\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"^\n" +
	"\x14ListSessionsResponse\x120\n" +
	"\bsessions\x18\x01 \x03(\v2\x14.loka.api.v1.SessionR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"=\n" +
	"\x15DestroySessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"%\n" +
	"\x13PauseSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14ResumeSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x15SetSessionModeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.loka.api.v1.ExecModeR\x04mode\"z\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\bcommands\x18\x02 \x03(\v2\x14.loka.api.v1.CommandR\bcommands\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\bR\bparallel\"M\n" +
	"\x13GetExecutionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\"\x95\x01\n" +
	"\x15ListExecutionsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.loka.api.v1.ExecStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"f\n" +
	"\x16ListExecutionsResponse\x126\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x16.loka.api.v1.ExecutionR\n" +
	"executions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"o\n" +
	"\x16CancelExecutionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12\x1d\n" +
	"\n" +
	"cancel_all\x18\x03 \x01(\bR\tcancelAll\"p\n" +
	"\x17StreamExecOutputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\"]\n" +
	"\vOutputChunk\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tis_stderr\x18\x02 \x01(\bR\bisStderr\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x7f\n" +
	"\x17CreateCheckpointRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.loka.api.v1.CheckpointTypeR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"Z\n" +
	"\x14GetCheckpointRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\"7\n" +
	"\x16ListCheckpointsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"^\n" +
	"\x18RestoreCheckpointRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\"]\n" +
	"\x17DeleteCheckpointRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\"+\n" +
	"\x15InstallPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13ListPackagesRequest\"H\n" +
	"\x14ListPackagesResponse\x120\n" +
	"\bpackages\x18\x01 \x03(\v2\x14.loka.api.v1.PackageR\bpackages\"5\n" +
	"\x17ValidatePackagesRequest\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\"\xa4\x01\n" +
	"\x18ValidatePackagesResponse\x12L\n" +
	"\aresults\x18\x01 \x03(\v22.loka.api.v1.ValidatePackagesResponse.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"F\n" +
	"\x14CreateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpackages\x18\x02 \x03(\tR\bpackages\"'\n" +
	"\x11GetProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13ListProfilesRequest\"O\n" +
	"\x14ListProfilesResponse\x127\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1b.loka.api.v1.PackageProfileR\bprofiles\"T\n" +
	"\x14UpdateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"*\n" +
	"\x14DeleteProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa9\x01\n" +
	"\x12ListWorkersRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.loka.api.v1.WorkerStatusR\x06status\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"Z\n" +
	"\x13ListWorkersResponse\x12-\n" +
	"\aworkers\x18\x01 \x03(\v2\x13.loka.api.v1.WorkerR\aworkers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\"\n" +
	"\x10GetWorkerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x12DrainWorkerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\";\n" +
	"\x13RemoveWorkerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force2\xee\x11\n" +
	"\x0eControlService\x12H\n" +
	"\rCreateSession\x12!.loka.api.v1.CreateSessionRequest\x1a\x14.loka.api.v1.Session\x12B\n" +
	"\n" +
	"GetSession\x12\x1e.loka.api.v1.GetSessionRequest\x1a\x14.loka.api.v1.Session\x12S\n" +
	"\fListSessions\x12 .loka.api.v1.ListSessionsRequest\x1a!.loka.api.v1.ListSessionsResponse\x12L\n" +
	"\x0eDestroySession\x12\".loka.api.v1.DestroySessionRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\fPauseSession\x12 .loka.api.v1.PauseSessionRequest\x1a\x14.loka.api.v1.Session\x12H\n" +
	"\rResumeSession\x12!.loka.api.v1.ResumeSessionRequest\x1a\x14.loka.api.v1.Session\x12J\n" +
	"\x0eSetSessionMode\x12\".loka.api.v1.SetSessionModeRequest\x1a\x14.loka.api.v1.Session\x128\n" +
	"\x04Exec\x12\x18.loka.api.v1.ExecRequest\x1a\x16.loka.api.v1.Execution\x12H\n" +
	"\fGetExecution\x12 .loka.api.v1.GetExecutionRequest\x1a\x16.loka.api.v1.Execution\x12Y\n" +
	"\x0eListExecutions\x12\".loka.api.v1.ListExecutionsRequest\x1a#.loka.api.v1.ListExecutionsResponse\x12N\n" +
	"\x0fCancelExecution\x12#.loka.api.v1.CancelExecutionRequest\x1a\x16.loka.api.v1.Execution\x12T\n" +
	"\x10StreamExecOutput\x12$.loka.api.v1.StreamExecOutputRequest\x1a\x18.loka.api.v1.OutputChunk0\x01\x12Q\n" +
	"\x10CreateCheckpoint\x12$.loka.api.v1.CreateCheckpointRequest\x1a\x17.loka.api.v1.Checkpoint\x12K\n" +
	"\rGetCheckpoint\x12!.loka.api.v1.GetCheckpointRequest\x1a\x17.loka.api.v1.Checkpoint\x12R\n" +
	"\x0fListCheckpoints\x12#.loka.api.v1.ListCheckpointsRequest\x1a\x1a.loka.api.v1.CheckpointDAG\x12P\n" +
	"\x11RestoreCheckpoint\x12%.loka.api.v1.RestoreCheckpointRequest\x1a\x14.loka.api.v1.Session\x12P\n" +
	"\x10DeleteCheckpoint\x12$.loka.api.v1.DeleteCheckpointRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eInstallPackage\x12\".loka.api.v1.InstallPackageRequest\x1a\x14.loka.api.v1.Package\x12S\n" +
	"\fListPackages\x12 .loka.api.v1.ListPackagesRequest\x1a!.loka.api.v1.ListPackagesResponse\x12_\n" +
	"\x10ValidatePackages\x12$.loka.api.v1.ValidatePackagesRequest\x1a%.loka.api.v1.ValidatePackagesResponse\x12O\n" +
	"\rCreateProfile\x12!.loka.api.v1.CreateProfileRequest\x1a\x1b.loka.api.v1.PackageProfile\x12I\n" +
	"\n" +
	"GetProfile\x12\x1e.loka.api.v1.GetProfileRequest\x1a\x1b.loka.api.v1.PackageProfile\x12S\n" +
	"\fListProfiles\x12 .loka.api.v1.ListProfilesRequest\x1a!.loka.api.v1.ListProfilesResponse\x12O\n" +
	"\rUpdateProfile\x12!.loka.api.v1.UpdateProfileRequest\x1a\x1b.loka.api.v1.PackageProfile\x12J\n" +
	"\rDeleteProfile\x12!.loka.api.v1.DeleteProfileRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\vListWorkers\x12\x1f.loka.api.v1.ListWorkersRequest\x1a .loka.api.v1.ListWorkersResponse\x12?\n" +
	"\tGetWorker\x12\x1d.loka.api.v1.GetWorkerRequest\x1a\x13.loka.api.v1.Worker\x12C\n" +
	"\vDrainWorker\x12\x1f.loka.api.v1.DrainWorkerRequest\x1a\x13.loka.api.v1.Worker\x12H\n" +
	"\fRemoveWorker\x12 .loka.api.v1.RemoveWorkerRequest\x1a\x16.google.protobuf.EmptyB#Z!github.com/rizqme/loka/api/lokav1b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_control_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),     // 0: loka.api.v1.CreateSessionRequest
	(*GetSessionRequest)(nil),        // 1: loka.api.v1.GetSessionRequest
	(*ListSessionsRequest)(nil),      // 2: loka.api.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),     // 3: loka.api.v1.ListSessionsResponse
	(*DestroySessionRequest)(nil),    // 4: loka.api.v1.DestroySessionRequest
	(*PauseSessionRequest)(nil),      // 5: loka.api.v1.PauseSessionRequest
	(*ResumeSessionRequest)(nil),     // 6: loka.api.v1.ResumeSessionRequest
	(*SetSessionModeRequest)(nil),    // 7: loka.api.v1.SetSessionModeRequest
	(*ExecRequest)(nil),              // 8: loka.api.v1.ExecRequest
	(*GetExecutionRequest)(nil),      // 9: loka.api.v1.GetExecutionRequest
	(*ListExecutionsRequest)(nil),    // 10: loka.api.v1.ListExecutionsRequest
	(*ListExecutionsResponse)(nil),   // 11: loka.api.v1.ListExecutionsResponse
	(*CancelExecutionRequest)(nil),   // 12: loka.api.v1.CancelExecutionRequest
	(*StreamExecOutputRequest)(nil),  // 13: loka.api.v1.StreamExecOutputRequest
	(*OutputChunk)(nil),              // 14: loka.api.v1.OutputChunk
	(*CreateCheckpointRequest)(nil),  // 15: loka.api.v1.CreateCheckpointRequest
	(*GetCheckpointRequest)(nil),     // 16: loka.api.v1.GetCheckpointRequest
	(*ListCheckpointsRequest)(nil),   // 17: loka.api.v1.ListCheckpointsRequest
	(*RestoreCheckpointRequest)(nil), // 18: loka.api.v1.RestoreCheckpointRequest
	(*DeleteCheckpointRequest)(nil),  // 19: loka.api.v1.DeleteCheckpointRequest
	(*InstallPackageRequest)(nil),    // 20: loka.api.v1.InstallPackageRequest
	(*ListPackagesRequest)(nil),      // 21: loka.api.v1.ListPackagesRequest
	(*ListPackagesResponse)(nil),     // 22: loka.api.v1.ListPackagesResponse
	(*ValidatePackagesRequest)(nil),  // 23: loka.api.v1.ValidatePackagesRequest
	(*ValidatePackagesResponse)(nil), // 24: loka.api.v1.ValidatePackagesResponse
	(*CreateProfileRequest)(nil),     // 25: loka.api.v1.CreateProfileRequest
	(*GetProfileRequest)(nil),        // 26: loka.api.v1.GetProfileRequest
	(*ListProfilesRequest)(nil),      // 27: loka.api.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),     // 28: loka.api.v1.ListProfilesResponse
	(*UpdateProfileRequest)(nil),     // 29: loka.api.v1.UpdateProfileRequest
	(*DeleteProfileRequest)(nil),     // 30: loka.api.v1.DeleteProfileRequest
	(*ListWorkersRequest)(nil),       // 31: loka.api.v1.ListWorkersRequest
	(*ListWorkersResponse)(nil),      // 32: loka.api.v1.ListWorkersResponse
	(*GetWorkerRequest)(nil),         // 33: loka.api.v1.GetWorkerRequest
	(*DrainWorkerRequest)(nil),       // 34: loka.api.v1.DrainWorkerRequest
	(*RemoveWorkerRequest)(nil),      // 35: loka.api.v1.RemoveWorkerRequest
	nil,                              // 36: loka.api.v1.CreateSessionRequest.LabelsEntry
	nil,                              // 37: loka.api.v1.CreateSessionRequest.WorkerLabelsEntry
	nil,                              // 38: loka.api.v1.ValidatePackagesResponse.ResultsEntry
	(ExecMode)(0),                    // 39: loka.api.v1.ExecMode
	(SessionStatus)(0),               // 40: loka.api.v1.SessionStatus
	(*Session)(nil),                  // 41: loka.api.v1.Session
	(*Command)(nil),                  // 42: loka.api.v1.Command
	(ExecStatus)(0),                  // 43: loka.api.v1.ExecStatus
	(*Execution)(nil),                // 44: loka.api.v1.Execution
	(CheckpointType)(0),              // 45: loka.api.v1.CheckpointType
	(*Package)(nil),                  // 46: loka.api.v1.Package
	(*PackageProfile)(nil),           // 47: loka.api.v1.PackageProfile
	(WorkerStatus)(0),                // 48: loka.api.v1.WorkerStatus
	(*Worker)(nil),                   // 49: loka.api.v1.Worker
	(*emptypb.Empty)(nil),            // 50: google.protobuf.Empty
	(*Checkpoint)(nil),               // 51: loka.api.v1.Checkpoint
	(*CheckpointDAG)(nil),            // 52: loka.api.v1.CheckpointDAG
}
var file_control_proto_depIdxs = []int32{
	39, // 0: loka.api.v1.CreateSessionRequest.mode:type_name -> loka.api.v1.ExecMode
	36, // 1: loka.api.v1.CreateSessionRequest.labels:type_name -> loka.api.v1.CreateSessionRequest.LabelsEntry
	37, // 2: loka.api.v1.CreateSessionRequest.worker_labels:type_name -> loka.api.v1.CreateSessionRequest.WorkerLabelsEntry
	40, // 3: loka.api.v1.ListSessionsRequest.status:type_name -> loka.api.v1.SessionStatus
	41, // 4: loka.api.v1.ListSessionsResponse.sessions:type_name -> loka.api.v1.Session
	39, // 5: loka.api.v1.SetSessionModeRequest.mode:type_name -> loka.api.v1.ExecMode
	42, // 6: loka.api.v1.ExecRequest.commands:type_name -> loka.api.v1.Command
	43, // 7: loka.api.v1.ListExecutionsRequest.status:type_name -> loka.api.v1.ExecStatus
	44, // 8: loka.api.v1.ListExecutionsResponse.executions:type_name -> loka.api.v1.Execution
	45, // 9: loka.api.v1.CreateCheckpointRequest.type:type_name -> loka.api.v1.CheckpointType
	46, // 10: loka.api.v1.ListPackagesResponse.packages:type_name -> loka.api.v1.Package
	38, // 11: loka.api.v1.ValidatePackagesResponse.results:type_name -> loka.api.v1.ValidatePackagesResponse.ResultsEntry
	47, // 12: loka.api.v1.ListProfilesResponse.profiles:type_name -> loka.api.v1.PackageProfile
	48, // 13: loka.api.v1.ListWorkersRequest.status:type_name -> loka.api.v1.WorkerStatus
	49, // 14: loka.api.v1.ListWorkersResponse.workers:type_name -> loka.api.v1.Worker
	0,  // 15: loka.api.v1.ControlService.CreateSession:input_type -> loka.api.v1.CreateSessionRequest
	1,  // 16: loka.api.v1.ControlService.GetSession:input_type -> loka.api.v1.GetSessionRequest
	2,  // 17: loka.api.v1.ControlService.ListSessions:input_type -> loka.api.v1.ListSessionsRequest
	4,  // 18: loka.api.v1.ControlService.DestroySession:input_type -> loka.api.v1.DestroySessionRequest
	5,  // 19: loka.api.v1.ControlService.PauseSession:input_type -> loka.api.v1.PauseSessionRequest
	6,  // 20: loka.api.v1.ControlService.ResumeSession:input_type -> loka.api.v1.ResumeSessionRequest
	7,  // 21: loka.api.v1.ControlService.SetSessionMode:input_type -> loka.api.v1.SetSessionModeRequest
	8,  // 22: loka.api.v1.ControlService.Exec:input_type -> loka.api.v1.ExecRequest
	9,  // 23: loka.api.v1.ControlService.GetExecution:input_type -> loka.api.v1.GetExecutionRequest
	10, // 24: loka.api.v1.ControlService.ListExecutions:input_type -> loka.api.v1.ListExecutionsRequest
	12, // 25: loka.api.v1.ControlService.CancelExecution:input_type -> loka.api.v1.CancelExecutionRequest
	13, // 26: loka.api.v1.ControlService.StreamExecOutput:input_type -> loka.api.v1.StreamExecOutputRequest
	15, // 27: loka.api.v1.ControlService.CreateCheckpoint:input_type -> loka.api.v1.CreateCheckpointRequest
	16, // 28: loka.api.v1.ControlService.GetCheckpoint:input_type -> loka.api.v1.GetCheckpointRequest
	17, // 29: loka.api.v1.ControlService.ListCheckpoints:input_type -> loka.api.v1.ListCheckpointsRequest
	18, // 30: loka.api.v1.ControlService.RestoreCheckpoint:input_type -> loka.api.v1.RestoreCheckpointRequest
	19, // 31: loka.api.v1.ControlService.DeleteCheckpoint:input_type -> loka.api.v1.DeleteCheckpointRequest
	20, // 32: loka.api.v1.ControlService.InstallPackage:input_type -> loka.api.v1.InstallPackageRequest
	21, // 33: loka.api.v1.ControlService.ListPackages:input_type -> loka.api.v1.ListPackagesRequest
	23, // 34: loka.api.v1.ControlService.ValidatePackages:input_type -> loka.api.v1.ValidatePackagesRequest
	25, // 35: loka.api.v1.ControlService.CreateProfile:input_type -> loka.api.v1.CreateProfileRequest
	26, // 36: loka.api.v1.ControlService.GetProfile:input_type -> loka.api.v1.GetProfileRequest
	27, // 37: loka.api.v1.ControlService.ListProfiles:input_type -> loka.api.v1.ListProfilesRequest
	29, // 38: loka.api.v1.ControlService.UpdateProfile:input_type -> loka.api.v1.UpdateProfileRequest
	30, // 39: loka.api.v1.ControlService.DeleteProfile:input_type -> loka.api.v1.DeleteProfileRequest
	31, // 40: loka.api.v1.ControlService.ListWorkers:input_type -> loka.api.v1.ListWorkersRequest
	33, // 41: loka.api.v1.ControlService.GetWorker:input_type -> loka.api.v1.GetWorkerRequest
	34, // 42: loka.api.v1.ControlService.DrainWorker:input_type -> loka.api.v1.DrainWorkerRequest
	35, // 43: loka.api.v1.ControlService.RemoveWorker:input_type -> loka.api.v1.RemoveWorkerRequest
	41, // 44: loka.api.v1.ControlService.CreateSession:output_type -> loka.api.v1.Session
	41, // 45: loka.api.v1.ControlService.GetSession:output_type -> loka.api.v1.Session
	3,  // 46: loka.api.v1.ControlService.ListSessions:output_type -> loka.api.v1.ListSessionsResponse
	50, // 47: loka.api.v1.ControlService.DestroySession:output_type -> google.protobuf.Empty
	41, // 48: loka.api.v1.ControlService.PauseSession:output_type -> loka.api.v1.Session
	41, // 49: loka.api.v1.ControlService.ResumeSession:output_type -> loka.api.v1.Session
	41, // 50: loka.api.v1.ControlService.SetSessionMode:output_type -> loka.api.v1.Session
	44, // 51: loka.api.v1.ControlService.Exec:output_type -> loka.api.v1.Execution
	44, // 52: loka.api.v1.ControlService.GetExecution:output_type -> loka.api.v1.Execution
	11, // 53: loka.api.v1.ControlService.ListExecutions:output_type -> loka.api.v1.ListExecutionsResponse
	44, // 54: loka.api.v1.ControlService.CancelExecution:output_type -> loka.api.v1.Execution
	14, // 55: loka.api.v1.ControlService.StreamExecOutput:output_type -> loka.api.v1.OutputChunk
	51, // 56: loka.api.v1.ControlService.CreateCheckpoint:output_type -> loka.api.v1.Checkpoint
	51, // 57: loka.api.v1.ControlService.GetCheckpoint:output_type -> loka.api.v1.Checkpoint
	52, // 58: loka.api.v1.ControlService.ListCheckpoints:output_type -> loka.api.v1.CheckpointDAG
	41, // 59: loka.api.v1.ControlService.RestoreCheckpoint:output_type -> loka.api.v1.Session
	50, // 60: loka.api.v1.ControlService.DeleteCheckpoint:output_type -> google.protobuf.Empty
	46, // 61: loka.api.v1.ControlService.InstallPackage:output_type -> loka.api.v1.Package
	22, // 62: loka.api.v1.ControlService.ListPackages:output_type -> loka.api.v1.ListPackagesResponse
	24, // 63: loka.api.v1.ControlService.ValidatePackages:output_type -> loka.api.v1.ValidatePackagesResponse
	47, // 64: loka.api.v1.ControlService.CreateProfile:output_type -> loka.api.v1.PackageProfile
	47, // 65: loka.api.v1.ControlService.GetProfile:output_type -> loka.api.v1.PackageProfile
	28, // 66: loka.api.v1.ControlService.ListProfiles:output_type -> loka.api.v1.ListProfilesResponse
	47, // 67: loka.api.v1.ControlService.UpdateProfile:output_type -> loka.api.v1.PackageProfile
	50, // 68: loka.api.v1.ControlService.DeleteProfile:output_type -> google.protobuf.Empty
	32, // 69: loka.api.v1.ControlService.ListWorkers:output_type -> loka.api.v1.ListWorkersResponse
	49, // 70: loka.api.v1.ControlService.GetWorker:output_type -> loka.api.v1.Worker
	49, // 71: loka.api.v1.ControlService.DrainWorker:output_type -> loka.api.v1.Worker
	50, // 72: loka.api.v1.ControlService.RemoveWorker:output_type -> google.protobuf.Empty
	44, // [44:73] is the sub-list for method output_type
	15, // [15:44] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
