// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: types.proto

package lokav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_CREATING    SessionStatus = 1
	SessionStatus_SESSION_STATUS_RUNNING     SessionStatus = 2
	SessionStatus_SESSION_STATUS_PAUSED      SessionStatus = 3
	SessionStatus_SESSION_STATUS_TERMINATING SessionStatus = 4
	SessionStatus_SESSION_STATUS_TERMINATED  SessionStatus = 5
	SessionStatus_SESSION_STATUS_ERROR       SessionStatus = 6
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_CREATING",
		2: "SESSION_STATUS_RUNNING",
		3: "SESSION_STATUS_PAUSED",
		4: "SESSION_STATUS_TERMINATING",
		5: "SESSION_STATUS_TERMINATED",
		6: "SESSION_STATUS_ERROR",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_CREATING":    1,
		"SESSION_STATUS_RUNNING":     2,
		"SESSION_STATUS_PAUSED":      3,
		"SESSION_STATUS_TERMINATING": 4,
		"SESSION_STATUS_TERMINATED":  5,
		"SESSION_STATUS_ERROR":       6,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type ExecMode int32

const (
	ExecMode_EXEC_MODE_UNSPECIFIED ExecMode = 0
	ExecMode_EXEC_MODE_EXPLORE     ExecMode = 1
	ExecMode_EXEC_MODE_EXECUTE     ExecMode = 2
	ExecMode_EXEC_MODE_ASK         ExecMode = 3
)

// Enum value maps for ExecMode.
var (
	ExecMode_name = map[int32]string{
		0: "EXEC_MODE_UNSPECIFIED",
		1: "EXEC_MODE_EXPLORE",
		2: "EXEC_MODE_EXECUTE",
		3: "EXEC_MODE_ASK",
	}
	ExecMode_value = map[string]int32{
		"EXEC_MODE_UNSPECIFIED": 0,
		"EXEC_MODE_EXPLORE":     1,
		"EXEC_MODE_EXECUTE":     2,
		"EXEC_MODE_ASK":         3,
	}
)

func (x ExecMode) Enum() *ExecMode {
	p := new(ExecMode)
	*p = x
	return p
}

func (x ExecMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecMode) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (ExecMode) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x ExecMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecMode.Descriptor instead.
func (ExecMode) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

type ExecStatus int32

const (
	ExecStatus_EXEC_STATUS_UNSPECIFIED ExecStatus = 0
	ExecStatus_EXEC_STATUS_PENDING     ExecStatus = 1
	ExecStatus_EXEC_STATUS_RUNNING     ExecStatus = 2
	ExecStatus_EXEC_STATUS_SUCCESS     ExecStatus = 3
	ExecStatus_EXEC_STATUS_FAILED      ExecStatus = 4
	ExecStatus_EXEC_STATUS_CANCELED    ExecStatus = 5
)

// Enum value maps for ExecStatus.
var (
	ExecStatus_name = map[int32]string{
		0: "EXEC_STATUS_UNSPECIFIED",
		1: "EXEC_STATUS_PENDING",
		2: "EXEC_STATUS_RUNNING",
		3: "EXEC_STATUS_SUCCESS",
		4: "EXEC_STATUS_FAILED",
		5: "EXEC_STATUS_CANCELED",
	}
	ExecStatus_value = map[string]int32{
		"EXEC_STATUS_UNSPECIFIED": 0,
		"EXEC_STATUS_PENDING":     1,
		"EXEC_STATUS_RUNNING":     2,
		"EXEC_STATUS_SUCCESS":     3,
		"EXEC_STATUS_FAILED":      4,
		"EXEC_STATUS_CANCELED":    5,
	}
)

func (x ExecStatus) Enum() *ExecStatus {
	p := new(ExecStatus)
	*p = x
	return p
}

func (x ExecStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[2].Descriptor()
}

func (ExecStatus) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[2]
}

func (x ExecStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecStatus.Descriptor instead.
func (ExecStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

type CheckpointType int32

const (
	CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED CheckpointType = 0
	CheckpointType_CHECKPOINT_TYPE_LIGHT       CheckpointType = 1
	CheckpointType_CHECKPOINT_TYPE_FULL        CheckpointType = 2
)

// Enum value maps for CheckpointType.
var (
	CheckpointType_name = map[int32]string{
		0: "CHECKPOINT_TYPE_UNSPECIFIED",
		1: "CHECKPOINT_TYPE_LIGHT",
		2: "CHECKPOINT_TYPE_FULL",
	}
	CheckpointType_value = map[string]int32{
		"CHECKPOINT_TYPE_UNSPECIFIED": 0,
		"CHECKPOINT_TYPE_LIGHT":       1,
		"CHECKPOINT_TYPE_FULL":        2,
	}
)

func (x CheckpointType) Enum() *CheckpointType {
	p := new(CheckpointType)
	*p = x
	return p
}

func (x CheckpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[3].Descriptor()
}

func (CheckpointType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[3]
}

func (x CheckpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointType.Descriptor instead.
func (CheckpointType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

type CheckpointStatus int32

const (
	CheckpointStatus_CHECKPOINT_STATUS_UNSPECIFIED CheckpointStatus = 0
	CheckpointStatus_CHECKPOINT_STATUS_CREATING    CheckpointStatus = 1
	CheckpointStatus_CHECKPOINT_STATUS_READY       CheckpointStatus = 2
	CheckpointStatus_CHECKPOINT_STATUS_FAILED      CheckpointStatus = 3
)

// Enum value maps for CheckpointStatus.
var (
	CheckpointStatus_name = map[int32]string{
		0: "CHECKPOINT_STATUS_UNSPECIFIED",
		1: "CHECKPOINT_STATUS_CREATING",
		2: "CHECKPOINT_STATUS_READY",
		3: "CHECKPOINT_STATUS_FAILED",
	}
	CheckpointStatus_value = map[string]int32{
		"CHECKPOINT_STATUS_UNSPECIFIED": 0,
		"CHECKPOINT_STATUS_CREATING":    1,
		"CHECKPOINT_STATUS_READY":       2,
		"CHECKPOINT_STATUS_FAILED":      3,
	}
)

func (x CheckpointStatus) Enum() *CheckpointStatus {
	p := new(CheckpointStatus)
	*p = x
	return p
}

func (x CheckpointStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[4].Descriptor()
}

func (CheckpointStatus) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[4]
}

func (x CheckpointStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointStatus.Descriptor instead.
func (CheckpointStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

type WorkerStatus int32

const (
	WorkerStatus_WORKER_STATUS_UNSPECIFIED WorkerStatus = 0
	WorkerStatus_WORKER_STATUS_REGISTERING WorkerStatus = 1
	WorkerStatus_WORKER_STATUS_READY       WorkerStatus = 2
	WorkerStatus_WORKER_STATUS_BUSY        WorkerStatus = 3
	WorkerStatus_WORKER_STATUS_DRAINING    WorkerStatus = 4
	WorkerStatus_WORKER_STATUS_SUSPECT     WorkerStatus = 5
	WorkerStatus_WORKER_STATUS_DEAD        WorkerStatus = 6
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "WORKER_STATUS_UNSPECIFIED",
		1: "WORKER_STATUS_REGISTERING",
		2: "WORKER_STATUS_READY",
		3: "WORKER_STATUS_BUSY",
		4: "WORKER_STATUS_DRAINING",
		5: "WORKER_STATUS_SUSPECT",
		6: "WORKER_STATUS_DEAD",
	}
	WorkerStatus_value = map[string]int32{
		"WORKER_STATUS_UNSPECIFIED": 0,
		"WORKER_STATUS_REGISTERING": 1,
		"WORKER_STATUS_READY":       2,
		"WORKER_STATUS_BUSY":        3,
		"WORKER_STATUS_DRAINING":    4,
		"WORKER_STATUS_SUSPECT":     5,
		"WORKER_STATUS_DEAD":        6,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[5].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[5]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        SessionStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=loka.api.v1.SessionStatus" json:"status,omitempty"`
	Mode          ExecMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=loka.api.v1.ExecMode" json:"mode,omitempty"`
	WorkerId      string                 `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Snapshot      string                 `protobuf:"bytes,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Packages      []string               `protobuf:"bytes,7,rep,name=packages,proto3" json:"packages,omitempty"`
	Profile       string                 `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	Vcpus         int32                  `protobuf:"varint,9,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,10,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetMode() ExecMode {
	if x != nil {
		return x.Mode
	}
	return ExecMode_EXEC_MODE_UNSPECIFIED
}

func (x *Session) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Session) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *Session) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *Session) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Session) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *Session) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Session) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Workdir       string                 `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits        *ResourceLimits        `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *Command) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Command) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores int32                  `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"` // 0 = unlimited
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`       // 0 = unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceLimits) GetCpuMillicores() int32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ResourceLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CommandResult) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        ExecStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=loka.api.v1.ExecStatus" json:"status,omitempty"`
	Parallel      bool                   `protobuf:"varint,4,opt,name=parallel,proto3" json:"parallel,omitempty"`
	Commands      []*Command             `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty"`
	Results       []*CommandResult       `protobuf:"bytes,6,rep,name=results,proto3" json:"results,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *Execution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Execution) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Execution) GetStatus() ExecStatus {
	if x != nil {
		return x.Status
	}
	return ExecStatus_EXEC_STATUS_UNSPECIFIED
}

func (x *Execution) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

func (x *Execution) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Execution) GetResults() []*CommandResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Execution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Execution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Type          CheckpointType         `protobuf:"varint,4,opt,name=type,proto3,enum=loka.api.v1.CheckpointType" json:"type,omitempty"`
	Status        CheckpointStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=loka.api.v1.CheckpointStatus" json:"status,omitempty"`
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *Checkpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkpoint) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Checkpoint) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Checkpoint) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *Checkpoint) GetStatus() CheckpointStatus {
	if x != nil {
		return x.Status
	}
	return CheckpointStatus_CHECKPOINT_STATUS_UNSPECIFIED
}

func (x *Checkpoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Checkpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CheckpointDAG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RootId        string                 `protobuf:"bytes,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	CurrentId     string                 `protobuf:"bytes,3,opt,name=current_id,json=currentId,proto3" json:"current_id,omitempty"`
	Checkpoints   []*Checkpoint          `protobuf:"bytes,4,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointDAG) Reset() {
	*x = CheckpointDAG{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointDAG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointDAG) ProtoMessage() {}

func (x *CheckpointDAG) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointDAG.ProtoReflect.Descriptor instead.
func (*CheckpointDAG) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *CheckpointDAG) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckpointDAG) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *CheckpointDAG) GetCurrentId() string {
	if x != nil {
		return x.CurrentId
	}
	return ""
}

func (x *CheckpointDAG) GetCheckpoints() []*Checkpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,6,opt,name=zone,proto3" json:"zone,omitempty"`
	Status        WorkerStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=loka.api.v1.WorkerStatus" json:"status,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capacity      *ResourceCapacity      `protobuf:"bytes,9,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,10,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	KvmAvailable  bool                   `protobuf:"varint,11,opt,name=kvm_available,json=kvmAvailable,proto3" json:"kvm_available,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worker) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Worker) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Worker) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Worker) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Worker) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Worker) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_WORKER_STATUS_UNSPECIFIED
}

func (x *Worker) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Worker) GetCapacity() *ResourceCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *Worker) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Worker) GetKvmAvailable() bool {
	if x != nil {
		return x.KvmAvailable
	}
	return false
}

func (x *Worker) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Worker) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type ResourceCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskMb        int64                  `protobuf:"varint,3,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceCapacity) Reset() {
	*x = ResourceCapacity{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCapacity) ProtoMessage() {}

func (x *ResourceCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCapacity.ProtoReflect.Descriptor instead.
func (*ResourceCapacity) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceCapacity) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceCapacity) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceCapacity) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedMb  int64                  `protobuf:"varint,2,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	DiskUsedMb    int64                  `protobuf:"varint,3,opt,name=disk_used_mb,json=diskUsedMb,proto3" json:"disk_used_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *ResourceUsage) GetDiskUsedMb() int64 {
	if x != nil {
		return x.DiskUsedMb
	}
	return 0
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Dependencies  []string               `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	SizeMb        int64                  `protobuf:"varint,4,opt,name=size_mb,json=sizeMb,proto3" json:"size_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Package) GetSizeMb() int64 {
	if x != nil {
		return x.SizeMb
	}
	return 0
}

type PackageProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Packages      []string               `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageProfile) Reset() {
	*x = PackageProfile{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageProfile) ProtoMessage() {}

func (x *PackageProfile) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageProfile.ProtoReflect.Descriptor instead.
func (*PackageProfile) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

func (x *PackageProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageProfile) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *PackageProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PackageProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\vloka.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x04\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.loka.api.v1.SessionStatusR\x06status\x12)\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x15.loka.api.v1.ExecModeR\x04mode\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bsnapshot\x18\x06 \x01(\tR\bsnapshot\x12\x1a\n" +
	"\bpackages\x18\a \x03(\tR\bpackages\x12\x18\n" +
	"\aprofile\x18\b \x01(\tR\aprofile\x12\x14\n" +
	"\x05vcpus\x18\t \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\n" +
	" \x01(\x05R\bmemoryMb\x128\n" +
	"\x06labels\x18\v \x03(\v2 .loka.api.v1.Session.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x12/\n" +
	"\x03env\x18\x05 \x03(\v2\x1d.loka.api.v1.Command.EnvEntryR\x03env\x123\n" +
	"\x06limits\x18\x06 \x01(\v2\x1b.loka.api.v1.ResourceLimitsR\x06limits\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x0eResourceLimits\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x05R\rcpuMillicores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"\xed\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\xe5\x02\n" +
	"\tExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.loka.api.v1.ExecStatusR\x06status\x12\x1a\n" +
	"\bparallel\x18\x04 \x01(\bR\bparallel\x120\n" +
	"\bcommands\x18\x05 \x03(\v2\x14.loka.api.v1.CommandR\bcommands\x124\n" +
	"\aresults\x18\x06 \x03(\v2\x1a.loka.api.v1.CommandResultR\aresults\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x91\x02\n" +
	"\n" +
	"Checkpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.loka.api.v1.CheckpointTypeR\x04type\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.loka.api.v1.CheckpointStatusR\x06status\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa1\x01\n" +
	"\rCheckpointDAG\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroot_id\x18\x02 \x01(\tR\x06rootId\x12\x1d\n" +
	"\n" +
	"current_id\x18\x03 \x01(\tR\tcurrentId\x129\n" +
	"\vcheckpoints\x18\x04 \x03(\v2\x17.loka.api.v1.CheckpointR\vcheckpoints\"\xbb\x04\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x06 \x01(\tR\x04zone\x121\n" +
	"\x06status\x18\a \x01(\x0e2\x19.loka.api.v1.WorkerStatusR\x06status\x127\n" +
	"\x06labels\x18\b \x03(\v2\x1f.loka.api.v1.Worker.LabelsEntryR\x06labels\x129\n" +
	"\bcapacity\x18\t \x01(\v2\x1d.loka.api.v1.ResourceCapacityR\bcapacity\x12#\n" +
	"\ragent_version\x18\n" +
	" \x01(\tR\fagentVersion\x12#\n" +
	"\rkvm_available\x18\v \x01(\bR\fkvmAvailable\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tlast_seen\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x10ResourceCapacity\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12\x17\n" +
	"\adisk_mb\x18\x03 \x01(\x03R\x06diskMb\"x\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0ememory_used_mb\x18\x02 \x01(\x03R\fmemoryUsedMb\x12 \n" +
	"\fdisk_used_mb\x18\x03 \x01(\x03R\n" +
	"diskUsedMb\"t\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fdependencies\x18\x03 \x03(\tR\fdependencies\x12\x17\n" +
	"\asize_mb\x18\x04 \x01(\x03R\x06sizeMb\"\xb6\x01\n" +
	"\x0ePackageProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpackages\x18\x02 \x03(\tR\bpackages\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xdc\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SESSION_STATUS_CREATING\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15SESSION_STATUS_PAUSED\x10\x03\x12\x1e\n" +
	"\x1aSESSION_STATUS_TERMINATING\x10\x04\x12\x1d\n" +
	"\x19SESSION_STATUS_TERMINATED\x10\x05\x12\x18\n" +
	"\x14SESSION_STATUS_ERROR\x10\x06*f\n" +
	"\bExecMode\x12\x19\n" +
	"\x15EXEC_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXEC_MODE_EXPLORE\x10\x01\x12\x15\n" +
	"\x11EXEC_MODE_EXECUTE\x10\x02\x12\x11\n" +
	"\rEXEC_MODE_ASK\x10\x03*\xa6\x01\n" +
	"\n" +
	"ExecStatus\x12\x1b\n" +
	"\x17EXEC_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXEC_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13EXEC_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13EXEC_STATUS_SUCCESS\x10\x03\x12\x16\n" +
	"\x12EXEC_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14EXEC_STATUS_CANCELED\x10\x05*f\n" +
	"\x0eCheckpointType\x12\x1f\n" +
	"\x1bCHECKPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHECKPOINT_TYPE_LIGHT\x10\x01\x12\x18\n" +
	"\x14CHECKPOINT_TYPE_FULL\x10\x02*\x90\x01\n" +
	"\x10CheckpointStatus\x12!\n" +
	"\x1dCHECKPOINT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCHECKPOINT_STATUS_CREATING\x10\x01\x12\x1b\n" +
	"\x17CHECKPOINT_STATUS_READY\x10\x02\x12\x1c\n" +
	"\x18CHECKPOINT_STATUS_FAILED\x10\x03*\xcc\x01\n" +
	"\fWorkerStatus\x12\x1d\n" +
	"\x19WORKER_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKER_STATUS_REGISTERING\x10\x01\x12\x17\n" +
	"\x13WORKER_STATUS_READY\x10\x02\x12\x16\n" +
	"\x12WORKER_STATUS_BUSY\x10\x03\x12\x1a\n" +
	"\x16WORKER_STATUS_DRAINING\x10\x04\x12\x19\n" +
	"\x15WORKER_STATUS_SUSPECT\x10\x05\x12\x16\n" +
	"\x12WORKER_STATUS_DEAD\x10\x06B#Z!github.com/rizqme/loka/api/lokav1b\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_types_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: loka.api.v1.SessionStatus
	(ExecMode)(0),                 // 1: loka.api.v1.ExecMode
	(ExecStatus)(0),               // 2: loka.api.v1.ExecStatus
	(CheckpointType)(0),           // 3: loka.api.v1.CheckpointType
	(CheckpointStatus)(0),         // 4: loka.api.v1.CheckpointStatus
	(WorkerStatus)(0),             // 5: loka.api.v1.WorkerStatus
	(*Session)(nil),               // 6: loka.api.v1.Session
	(*Command)(nil),               // 7: loka.api.v1.Command
	(*ResourceLimits)(nil),        // 8: loka.api.v1.ResourceLimits
	(*CommandResult)(nil),         // 9: loka.api.v1.CommandResult
	(*Execution)(nil),             // 10: loka.api.v1.Execution
	(*Checkpoint)(nil),            // 11: loka.api.v1.Checkpoint
	(*CheckpointDAG)(nil),         // 12: loka.api.v1.CheckpointDAG
	(*Worker)(nil),                // 13: loka.api.v1.Worker
	(*ResourceCapacity)(nil),      // 14: loka.api.v1.ResourceCapacity
	(*ResourceUsage)(nil),         // 15: loka.api.v1.ResourceUsage
	(*Package)(nil),               // 16: loka.api.v1.Package
	(*PackageProfile)(nil),        // 17: loka.api.v1.PackageProfile
	nil,                           // 18: loka.api.v1.Session.LabelsEntry
	nil,                           // 19: loka.api.v1.Command.EnvEntry
	nil,                           // 20: loka.api.v1.Worker.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_types_proto_depIdxs = []int32{
	0,  // 0: loka.api.v1.Session.status:type_name -> loka.api.v1.SessionStatus
	1,  // 1: loka.api.v1.Session.mode:type_name -> loka.api.v1.ExecMode
	18, // 2: loka.api.v1.Session.labels:type_name -> loka.api.v1.Session.LabelsEntry
	21, // 3: loka.api.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	21, // 4: loka.api.v1.Session.updated_at:type_name -> google.protobuf.Timestamp
	19, // 5: loka.api.v1.Command.env:type_name -> loka.api.v1.Command.EnvEntry
	8,  // 6: loka.api.v1.Command.limits:type_name -> loka.api.v1.ResourceLimits
	21, // 7: loka.api.v1.CommandResult.started_at:type_name -> google.protobuf.Timestamp
	21, // 8: loka.api.v1.CommandResult.ended_at:type_name -> google.protobuf.Timestamp
	2,  // 9: loka.api.v1.Execution.status:type_name -> loka.api.v1.ExecStatus
	7,  // 10: loka.api.v1.Execution.commands:type_name -> loka.api.v1.Command
	9,  // 11: loka.api.v1.Execution.results:type_name -> loka.api.v1.CommandResult
	21, // 12: loka.api.v1.Execution.created_at:type_name -> google.protobuf.Timestamp
	21, // 13: loka.api.v1.Execution.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 14: loka.api.v1.Checkpoint.type:type_name -> loka.api.v1.CheckpointType
	4,  // 15: loka.api.v1.Checkpoint.status:type_name -> loka.api.v1.CheckpointStatus
	21, // 16: loka.api.v1.Checkpoint.created_at:type_name -> google.protobuf.Timestamp
	11, // 17: loka.api.v1.CheckpointDAG.checkpoints:type_name -> loka.api.v1.Checkpoint
	5,  // 18: loka.api.v1.Worker.status:type_name -> loka.api.v1.WorkerStatus
	20, // 19: loka.api.v1.Worker.labels:type_name -> loka.api.v1.Worker.LabelsEntry
	14, // 20: loka.api.v1.Worker.capacity:type_name -> loka.api.v1.ResourceCapacity
	21, // 21: loka.api.v1.Worker.created_at:type_name -> google.protobuf.Timestamp
	21, // 22: loka.api.v1.Worker.last_seen:type_name -> google.protobuf.Timestamp
	21, // 23: loka.api.v1.PackageProfile.created_at:type_name -> google.protobuf.Timestamp
	21, // 24: loka.api.v1.PackageProfile.updated_at:type_name -> google.protobuf.Timestamp
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
