// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: worker.proto

package lokav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Register_FullMethodName                 = "/loka.api.v1.WorkerService/Register"
	WorkerService_Heartbeat_FullMethodName                = "/loka.api.v1.WorkerService/Heartbeat"
	WorkerService_ReportSessionStatus_FullMethodName      = "/loka.api.v1.WorkerService/ReportSessionStatus"
	WorkerService_ReportCheckpointComplete_FullMethodName = "/loka.api.v1.WorkerService/ReportCheckpointComplete"
	WorkerService_ReportExecComplete_FullMethodName       = "/loka.api.v1.WorkerService/ReportExecComplete"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService is the internal gRPC service that workers connect to on the control plane.
type WorkerServiceClient interface {
	// Register is called once when the worker starts.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat is a bidirectional stream.
	// Worker → CP: periodic heartbeats with resource metrics.
	// CP → Worker: commands (launch, stop, checkpoint, drain, etc.).
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatMessage, WorkerCommand], error)
	// ReportSessionStatus is called by workers to report session state changes.
	ReportSessionStatus(ctx context.Context, in *SessionStatusReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReportCheckpointComplete is called when a checkpoint operation finishes.
	ReportCheckpointComplete(ctx context.Context, in *CheckpointReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReportExecComplete is called when a command execution finishes.
	ReportExecComplete(ctx context.Context, in *ExecReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatMessage, WorkerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatMessage, WorkerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatMessage, WorkerCommand]

func (c *workerServiceClient) ReportSessionStatus(ctx context.Context, in *SessionStatusReport, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkerService_ReportSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReportCheckpointComplete(ctx context.Context, in *CheckpointReport, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkerService_ReportCheckpointComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReportExecComplete(ctx context.Context, in *ExecReport, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkerService_ReportExecComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService is the internal gRPC service that workers connect to on the control plane.
type WorkerServiceServer interface {
	// Register is called once when the worker starts.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat is a bidirectional stream.
	// Worker → CP: periodic heartbeats with resource metrics.
	// CP → Worker: commands (launch, stop, checkpoint, drain, etc.).
	Heartbeat(grpc.BidiStreamingServer[HeartbeatMessage, WorkerCommand]) error
	// ReportSessionStatus is called by workers to report session state changes.
	ReportSessionStatus(context.Context, *SessionStatusReport) (*emptypb.Empty, error)
	// ReportCheckpointComplete is called when a checkpoint operation finishes.
	ReportCheckpointComplete(context.Context, *CheckpointReport) (*emptypb.Empty, error)
	// ReportExecComplete is called when a command execution finishes.
	ReportExecComplete(context.Context, *ExecReport) (*emptypb.Empty, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatMessage, WorkerCommand]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) ReportSessionStatus(context.Context, *SessionStatusReport) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSessionStatus not implemented")
}
func (UnimplementedWorkerServiceServer) ReportCheckpointComplete(context.Context, *CheckpointReport) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCheckpointComplete not implemented")
}
func (UnimplementedWorkerServiceServer) ReportExecComplete(context.Context, *ExecReport) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportExecComplete not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatMessage, WorkerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatMessage, WorkerCommand]

func _WorkerService_ReportSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReportSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReportSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReportSessionStatus(ctx, req.(*SessionStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReportCheckpointComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReportCheckpointComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReportCheckpointComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReportCheckpointComplete(ctx, req.(*CheckpointReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReportExecComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReportExecComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReportExecComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReportExecComplete(ctx, req.(*ExecReport))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loka.api.v1.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkerService_Register_Handler,
		},
		{
			MethodName: "ReportSessionStatus",
			Handler:    _WorkerService_ReportSessionStatus_Handler,
		},
		{
			MethodName: "ReportCheckpointComplete",
			Handler:    _WorkerService_ReportCheckpointComplete_Handler,
		},
		{
			MethodName: "ReportExecComplete",
			Handler:    _WorkerService_ReportExecComplete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _WorkerService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "worker.proto",
}
