// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: worker.proto

package lokav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Capacity      *ResourceCapacity      `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string                 `protobuf:"bytes,8,opt,name=zone,proto3" json:"zone,omitempty"`
	KvmAvailable  bool                   `protobuf:"varint,9,opt,name=kvm_available,json=kvmAvailable,proto3" json:"kvm_available,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,10,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetCapacity() *ResourceCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *RegisterRequest) GetKvmAvailable() bool {
	if x != nil {
		return x.KvmAvailable
	}
	return false
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Config        *WorkerRuntimeConfig   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *WorkerRuntimeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type WorkerRuntimeConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	ObjectStore              *ObjectStoreConfig     `protobuf:"bytes,2,opt,name=object_store,json=objectStore,proto3" json:"object_store,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *WorkerRuntimeConfig) Reset() {
	*x = WorkerRuntimeConfig{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRuntimeConfig) ProtoMessage() {}

func (x *WorkerRuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRuntimeConfig.ProtoReflect.Descriptor instead.
func (*WorkerRuntimeConfig) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerRuntimeConfig) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *WorkerRuntimeConfig) GetObjectStore() *ObjectStoreConfig {
	if x != nil {
		return x.ObjectStore
	}
	return nil
}

type ObjectStoreConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "s3", "gcs", "local"
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"` // Credentials are rotated via the heartbeat stream.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectStoreConfig) Reset() {
	*x = ObjectStoreConfig{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectStoreConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStoreConfig) ProtoMessage() {}

func (x *ObjectStoreConfig) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStoreConfig.ProtoReflect.Descriptor instead.
func (*ObjectStoreConfig) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectStoreConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObjectStoreConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectStoreConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CurrentUsage  *ResourceUsage         `protobuf:"bytes,3,opt,name=current_usage,json=currentUsage,proto3" json:"current_usage,omitempty"`
	Sessions      []*RunningSession      `protobuf:"bytes,4,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Status        WorkerStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=loka.api.v1.WorkerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatMessage) GetCurrentUsage() *ResourceUsage {
	if x != nil {
		return x.CurrentUsage
	}
	return nil
}

func (x *HeartbeatMessage) GetSessions() []*RunningSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *HeartbeatMessage) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_WORKER_STATUS_UNSPECIFIED
}

type RunningSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=loka.api.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningSession) Reset() {
	*x = RunningSession{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningSession) ProtoMessage() {}

func (x *RunningSession) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningSession.ProtoReflect.Descriptor instead.
func (*RunningSession) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *RunningSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunningSession) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

type WorkerCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // Unique ID for tracking.
	// Types that are valid to be assigned to Command:
	//
	//	*WorkerCommand_LaunchSession
	//	*WorkerCommand_StopSession
	//	*WorkerCommand_ExecCommand
	//	*WorkerCommand_CreateCheckpoint
	//	*WorkerCommand_RestoreCheckpoint
	//	*WorkerCommand_SetMode
	//	*WorkerCommand_Drain
	Command       isWorkerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerCommand) Reset() {
	*x = WorkerCommand{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCommand) ProtoMessage() {}

func (x *WorkerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCommand.ProtoReflect.Descriptor instead.
func (*WorkerCommand) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *WorkerCommand) GetCommand() isWorkerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WorkerCommand) GetLaunchSession() *LaunchSessionCmd {
	if x != nil {
		if x, ok := x.Command.(*WorkerCommand_LaunchSession); ok {
			return x.LaunchSession
		}
	}
	return nil
}

func (x *WorkerCommand) GetStopSession() *StopSessionCmd {
	if x != nil {
		if x, ok := x.Command.(*WorkerCommand_StopSession); ok {
			return x.StopSession
		}
	}
	return nil
}

func (x *WorkerCommand) GetExecCommand() *ExecCommandCmd {
	if x != nil {
		if x, ok := x.Command.(*WorkerCommand_ExecCommand); ok {
			return x.ExecCommand
		}
	}
	return nil
}

func (x *WorkerCommand) GetCreateCheckpoint() *CreateCheckpointCmd {
	if x != nil {
		if x, ok := x.Command.(*WorkerCommand_CreateCheckpoint); ok {
			return x.CreateCheckpoint
		}
	}
	return nil
}

func (x *WorkerCommand) GetRestoreCheckpoint() *RestoreCheckpointCmd {
	if x != nil {
		if x, ok := x.Command.(*WorkerCommand_RestoreCheckpoint); ok {
			return x.RestoreCheckpoint
		}
	}
	return nil
}

func (x *WorkerCommand) GetSetMode() *SetModeCmd {
	if x != nil {
		if x, ok := x.Command.(*WorkerCommand_SetMode); ok {
			return x.SetMode
		}
	}
	return nil
}

func (x *WorkerCommand) GetDrain() *DrainCmd {
	if x != nil {
		if x, ok := x.Command.(*WorkerCommand_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

type isWorkerCommand_Command interface {
	isWorkerCommand_Command()
}

type WorkerCommand_LaunchSession struct {
	LaunchSession *LaunchSessionCmd `protobuf:"bytes,2,opt,name=launch_session,json=launchSession,proto3,oneof"`
}

type WorkerCommand_StopSession struct {
	StopSession *StopSessionCmd `protobuf:"bytes,3,opt,name=stop_session,json=stopSession,proto3,oneof"`
}

type WorkerCommand_ExecCommand struct {
	ExecCommand *ExecCommandCmd `protobuf:"bytes,4,opt,name=exec_command,json=execCommand,proto3,oneof"`
}

type WorkerCommand_CreateCheckpoint struct {
	CreateCheckpoint *CreateCheckpointCmd `protobuf:"bytes,5,opt,name=create_checkpoint,json=createCheckpoint,proto3,oneof"`
}

type WorkerCommand_RestoreCheckpoint struct {
	RestoreCheckpoint *RestoreCheckpointCmd `protobuf:"bytes,6,opt,name=restore_checkpoint,json=restoreCheckpoint,proto3,oneof"`
}

type WorkerCommand_SetMode struct {
	SetMode *SetModeCmd `protobuf:"bytes,7,opt,name=set_mode,json=setMode,proto3,oneof"`
}

type WorkerCommand_Drain struct {
	Drain *DrainCmd `protobuf:"bytes,8,opt,name=drain,proto3,oneof"`
}

func (*WorkerCommand_LaunchSession) isWorkerCommand_Command() {}

func (*WorkerCommand_StopSession) isWorkerCommand_Command() {}

func (*WorkerCommand_ExecCommand) isWorkerCommand_Command() {}

func (*WorkerCommand_CreateCheckpoint) isWorkerCommand_Command() {}

func (*WorkerCommand_RestoreCheckpoint) isWorkerCommand_Command() {}

func (*WorkerCommand_SetMode) isWorkerCommand_Command() {}

func (*WorkerCommand_Drain) isWorkerCommand_Command() {}

type LaunchSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Snapshot      string                 `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"` // Object store key for base snapshot.
	Packages      []string               `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	InitialMode   ExecMode               `protobuf:"varint,4,opt,name=initial_mode,json=initialMode,proto3,enum=loka.api.v1.ExecMode" json:"initial_mode,omitempty"`
	Vcpus         int32                  `protobuf:"varint,5,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchSessionCmd) Reset() {
	*x = LaunchSessionCmd{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchSessionCmd) ProtoMessage() {}

func (x *LaunchSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchSessionCmd.ProtoReflect.Descriptor instead.
func (*LaunchSessionCmd) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *LaunchSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LaunchSessionCmd) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *LaunchSessionCmd) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *LaunchSessionCmd) GetInitialMode() ExecMode {
	if x != nil {
		return x.InitialMode
	}
	return ExecMode_EXEC_MODE_UNSPECIFIED
}

func (x *LaunchSessionCmd) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *LaunchSessionCmd) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type StopSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionCmd) Reset() {
	*x = StopSessionCmd{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionCmd) ProtoMessage() {}

func (x *StopSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionCmd.ProtoReflect.Descriptor instead.
func (*StopSessionCmd) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *StopSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopSessionCmd) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ExecCommandCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Commands      []*Command             `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	Parallel      bool                   `protobuf:"varint,4,opt,name=parallel,proto3" json:"parallel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandCmd) Reset() {
	*x = ExecCommandCmd{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandCmd) ProtoMessage() {}

func (x *ExecCommandCmd) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandCmd.ProtoReflect.Descriptor instead.
func (*ExecCommandCmd) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *ExecCommandCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecCommandCmd) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecCommandCmd) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ExecCommandCmd) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

type CreateCheckpointCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Type          CheckpointType         `protobuf:"varint,3,opt,name=type,proto3,enum=loka.api.v1.CheckpointType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckpointCmd) Reset() {
	*x = CreateCheckpointCmd{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckpointCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckpointCmd) ProtoMessage() {}

func (x *CreateCheckpointCmd) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckpointCmd.ProtoReflect.Descriptor instead.
func (*CreateCheckpointCmd) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCheckpointCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateCheckpointCmd) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CreateCheckpointCmd) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

type RestoreCheckpointCmd struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SessionId    string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointId string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// Object store paths to pull.
	OverlayKey    string `protobuf:"bytes,3,opt,name=overlay_key,json=overlayKey,proto3" json:"overlay_key,omitempty"`
	VmstateKey    string `protobuf:"bytes,4,opt,name=vmstate_key,json=vmstateKey,proto3" json:"vmstate_key,omitempty"` // Empty for light checkpoints.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCheckpointCmd) Reset() {
	*x = RestoreCheckpointCmd{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCheckpointCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCheckpointCmd) ProtoMessage() {}

func (x *RestoreCheckpointCmd) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCheckpointCmd.ProtoReflect.Descriptor instead.
func (*RestoreCheckpointCmd) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreCheckpointCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RestoreCheckpointCmd) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *RestoreCheckpointCmd) GetOverlayKey() string {
	if x != nil {
		return x.OverlayKey
	}
	return ""
}

func (x *RestoreCheckpointCmd) GetVmstateKey() string {
	if x != nil {
		return x.VmstateKey
	}
	return ""
}

type SetModeCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Mode          ExecMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=loka.api.v1.ExecMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModeCmd) Reset() {
	*x = SetModeCmd{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModeCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModeCmd) ProtoMessage() {}

func (x *SetModeCmd) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModeCmd.ProtoReflect.Descriptor instead.
func (*SetModeCmd) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *SetModeCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetModeCmd) GetMode() ExecMode {
	if x != nil {
		return x.Mode
	}
	return ExecMode_EXEC_MODE_UNSPECIFIED
}

type DrainCmd struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds int32                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DrainCmd) Reset() {
	*x = DrainCmd{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainCmd) ProtoMessage() {}

func (x *DrainCmd) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainCmd.ProtoReflect.Descriptor instead.
func (*DrainCmd) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

func (x *DrainCmd) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SessionStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=loka.api.v1.SessionStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusReport) Reset() {
	*x = SessionStatusReport{}
	mi := &file_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusReport) ProtoMessage() {}

func (x *SessionStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusReport.ProtoReflect.Descriptor instead.
func (*SessionStatusReport) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{14}
}

func (x *SessionStatusReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SessionStatusReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusReport) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionStatusReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CheckpointReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,3,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OverlayKey    string                 `protobuf:"bytes,6,opt,name=overlay_key,json=overlayKey,proto3" json:"overlay_key,omitempty"` // Object store key where overlay was uploaded.
	VmstateKey    string                 `protobuf:"bytes,7,opt,name=vmstate_key,json=vmstateKey,proto3" json:"vmstate_key,omitempty"` // Object store key where VM state was uploaded.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointReport) Reset() {
	*x = CheckpointReport{}
	mi := &file_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointReport) ProtoMessage() {}

func (x *CheckpointReport) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointReport.ProtoReflect.Descriptor instead.
func (*CheckpointReport) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{15}
}

func (x *CheckpointReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CheckpointReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckpointReport) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CheckpointReport) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckpointReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CheckpointReport) GetOverlayKey() string {
	if x != nil {
		return x.OverlayKey
	}
	return ""
}

func (x *CheckpointReport) GetVmstateKey() string {
	if x != nil {
		return x.VmstateKey
	}
	return ""
}

type ExecReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecId        string                 `protobuf:"bytes,3,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Status        ExecStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=loka.api.v1.ExecStatus" json:"status,omitempty"`
	Results       []*CommandResult       `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecReport) Reset() {
	*x = ExecReport{}
	mi := &file_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecReport) ProtoMessage() {}

func (x *ExecReport) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecReport.ProtoReflect.Descriptor instead.
func (*ExecReport) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{16}
}

func (x *ExecReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ExecReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecReport) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecReport) GetStatus() ExecStatus {
	if x != nil {
		return x.Status
	}
	return ExecStatus_EXEC_STATUS_UNSPECIFIED
}

func (x *ExecReport) GetResults() []*CommandResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\vloka.api.v1\x1a\vtypes.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x03\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x129\n" +
	"\bcapacity\x18\x05 \x01(\v2\x1d.loka.api.v1.ResourceCapacityR\bcapacity\x12@\n" +
	"\x06labels\x18\x06 \x03(\v2(.loka.api.v1.RegisterRequest.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\b \x01(\tR\x04zone\x12#\n" +
	"\rkvm_available\x18\t \x01(\bR\fkvmAvailable\x12#\n" +
	"\ragent_version\x18\n" +
	" \x01(\tR\fagentVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x128\n" +
	"\x06config\x18\x02 \x01(\v2 .loka.api.v1.WorkerRuntimeConfigR\x06config\"\x96\x01\n" +
	"\x13WorkerRuntimeConfig\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\x05R\x18heartbeatIntervalSeconds\x12A\n" +
	"\fobject_store\x18\x02 \x01(\v2\x1e.loka.api.v1.ObjectStoreConfigR\vobjectStore\"W\n" +
	"\x11ObjectStoreConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\x96\x02\n" +
	"\x10HeartbeatMessage\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\rcurrent_usage\x18\x03 \x01(\v2\x1a.loka.api.v1.ResourceUsageR\fcurrentUsage\x127\n" +
	"\bsessions\x18\x04 \x03(\v2\x1b.loka.api.v1.RunningSessionR\bsessions\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.loka.api.v1.WorkerStatusR\x06status\"c\n" +
	"\x0eRunningSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.loka.api.v1.SessionStatusR\x06status\"\x8f\x04\n" +
	"\rWorkerCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12F\n" +
	"\x0elaunch_session\x18\x02 \x01(\v2\x1d.loka.api.v1.LaunchSessionCmdH\x00R\rlaunchSession\x12@\n" +
	"\fstop_session\x18\x03 \x01(\v2\x1b.loka.api.v1.StopSessionCmdH\x00R\vstopSession\x12@\n" +
	"\fexec_command\x18\x04 \x01(\v2\x1b.loka.api.v1.ExecCommandCmdH\x00R\vexecCommand\x12O\n" +
	"\x11create_checkpoint\x18\x05 \x01(\v2 .loka.api.v1.CreateCheckpointCmdH\x00R\x10createCheckpoint\x12R\n" +
	"\x12restore_checkpoint\x18\x06 \x01(\v2!.loka.api.v1.RestoreCheckpointCmdH\x00R\x11restoreCheckpoint\x124\n" +
	"\bset_mode\x18\a \x01(\v2\x17.loka.api.v1.SetModeCmdH\x00R\asetMode\x12-\n" +
	"\x05drain\x18\b \x01(\v2\x15.loka.api.v1.DrainCmdH\x00R\x05drainB\t\n" +
	"\acommand\"\xd6\x01\n" +
	"\x10LaunchSessionCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsnapshot\x18\x02 \x01(\tR\bsnapshot\x12\x1a\n" +
	"\bpackages\x18\x03 \x03(\tR\bpackages\x128\n" +
	"\finitial_mode\x18\x04 \x01(\x0e2\x15.loka.api.v1.ExecModeR\vinitialMode\x12\x14\n" +
	"\x05vcpus\x18\x05 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x06 \x01(\x05R\bmemoryMb\"E\n" +
	"\x0eStopSessionCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x96\x01\n" +
	"\x0eExecCommandCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x120\n" +
	"\bcommands\x18\x03 \x03(\v2\x14.loka.api.v1.CommandR\bcommands\x12\x1a\n" +
	"\bparallel\x18\x04 \x01(\bR\bparallel\"\x8a\x01\n" +
	"\x13CreateCheckpointCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.loka.api.v1.CheckpointTypeR\x04type\"\x9c\x01\n" +
	"\x14RestoreCheckpointCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12\x1f\n" +
	"\voverlay_key\x18\x03 \x01(\tR\n" +
	"overlayKey\x12\x1f\n" +
	"\vvmstate_key\x18\x04 \x01(\tR\n" +
	"vmstateKey\"V\n" +
	"\n" +
	"SetModeCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.loka.api.v1.ExecModeR\x04mode\"3\n" +
	"\bDrainCmd\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x05R\x0etimeoutSeconds\"\xaa\x01\n" +
	"\x13SessionStatusReport\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.loka.api.v1.SessionStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xf4\x01\n" +
	"\x10CheckpointReport\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12#\n" +
	"\rcheckpoint_id\x18\x03 \x01(\tR\fcheckpointId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\voverlay_key\x18\x06 \x01(\tR\n" +
	"overlayKey\x12\x1f\n" +
	"\vvmstate_key\x18\a \x01(\tR\n" +
	"vmstateKey\"\xed\x01\n" +
	"\n" +
	"ExecReport\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\aexec_id\x18\x03 \x01(\tR\x06execId\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.loka.api.v1.ExecStatusR\x06status\x124\n" +
	"\aresults\x18\x05 \x03(\v2\x1a.loka.api.v1.CommandResultR\aresults\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage2\x8f\x03\n" +
	"\rWorkerService\x12G\n" +
	"\bRegister\x12\x1c.loka.api.v1.RegisterRequest\x1a\x1d.loka.api.v1.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.loka.api.v1.HeartbeatMessage\x1a\x1a.loka.api.v1.WorkerCommand(\x010\x01\x12O\n" +
	"\x13ReportSessionStatus\x12 .loka.api.v1.SessionStatusReport\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x18ReportCheckpointComplete\x12\x1d.loka.api.v1.CheckpointReport\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x12ReportExecComplete\x12\x17.loka.api.v1.ExecReport\x1a\x16.google.protobuf.EmptyB#Z!github.com/rizqme/loka/api/lokav1b\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_worker_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: loka.api.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: loka.api.v1.RegisterResponse
	(*WorkerRuntimeConfig)(nil),   // 2: loka.api.v1.WorkerRuntimeConfig
	(*ObjectStoreConfig)(nil),     // 3: loka.api.v1.ObjectStoreConfig
	(*HeartbeatMessage)(nil),      // 4: loka.api.v1.HeartbeatMessage
	(*RunningSession)(nil),        // 5: loka.api.v1.RunningSession
	(*WorkerCommand)(nil),         // 6: loka.api.v1.WorkerCommand
	(*LaunchSessionCmd)(nil),      // 7: loka.api.v1.LaunchSessionCmd
	(*StopSessionCmd)(nil),        // 8: loka.api.v1.StopSessionCmd
	(*ExecCommandCmd)(nil),        // 9: loka.api.v1.ExecCommandCmd
	(*CreateCheckpointCmd)(nil),   // 10: loka.api.v1.CreateCheckpointCmd
	(*RestoreCheckpointCmd)(nil),  // 11: loka.api.v1.RestoreCheckpointCmd
	(*SetModeCmd)(nil),            // 12: loka.api.v1.SetModeCmd
	(*DrainCmd)(nil),              // 13: loka.api.v1.DrainCmd
	(*SessionStatusReport)(nil),   // 14: loka.api.v1.SessionStatusReport
	(*CheckpointReport)(nil),      // 15: loka.api.v1.CheckpointReport
	(*ExecReport)(nil),            // 16: loka.api.v1.ExecReport
	nil,                           // 17: loka.api.v1.RegisterRequest.LabelsEntry
	(*ResourceCapacity)(nil),      // 18: loka.api.v1.ResourceCapacity
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*ResourceUsage)(nil),         // 20: loka.api.v1.ResourceUsage
	(WorkerStatus)(0),             // 21: loka.api.v1.WorkerStatus
	(SessionStatus)(0),            // 22: loka.api.v1.SessionStatus
	(ExecMode)(0),                 // 23: loka.api.v1.ExecMode
	(*Command)(nil),               // 24: loka.api.v1.Command
	(CheckpointType)(0),           // 25: loka.api.v1.CheckpointType
	(ExecStatus)(0),               // 26: loka.api.v1.ExecStatus
	(*CommandResult)(nil),         // 27: loka.api.v1.CommandResult
	(*emptypb.Empty)(nil),         // 28: google.protobuf.Empty
}
var file_worker_proto_depIdxs = []int32{
	18, // 0: loka.api.v1.RegisterRequest.capacity:type_name -> loka.api.v1.ResourceCapacity
	17, // 1: loka.api.v1.RegisterRequest.labels:type_name -> loka.api.v1.RegisterRequest.LabelsEntry
	2,  // 2: loka.api.v1.RegisterResponse.config:type_name -> loka.api.v1.WorkerRuntimeConfig
	3,  // 3: loka.api.v1.WorkerRuntimeConfig.object_store:type_name -> loka.api.v1.ObjectStoreConfig
	19, // 4: loka.api.v1.HeartbeatMessage.timestamp:type_name -> google.protobuf.Timestamp
	20, // 5: loka.api.v1.HeartbeatMessage.current_usage:type_name -> loka.api.v1.ResourceUsage
	5,  // 6: loka.api.v1.HeartbeatMessage.sessions:type_name -> loka.api.v1.RunningSession
	21, // 7: loka.api.v1.HeartbeatMessage.status:type_name -> loka.api.v1.WorkerStatus
	22, // 8: loka.api.v1.RunningSession.status:type_name -> loka.api.v1.SessionStatus
	7,  // 9: loka.api.v1.WorkerCommand.launch_session:type_name -> loka.api.v1.LaunchSessionCmd
	8,  // 10: loka.api.v1.WorkerCommand.stop_session:type_name -> loka.api.v1.StopSessionCmd
	9,  // 11: loka.api.v1.WorkerCommand.exec_command:type_name -> loka.api.v1.ExecCommandCmd
	10, // 12: loka.api.v1.WorkerCommand.create_checkpoint:type_name -> loka.api.v1.CreateCheckpointCmd
	11, // 13: loka.api.v1.WorkerCommand.restore_checkpoint:type_name -> loka.api.v1.RestoreCheckpointCmd
	12, // 14: loka.api.v1.WorkerCommand.set_mode:type_name -> loka.api.v1.SetModeCmd
	13, // 15: loka.api.v1.WorkerCommand.drain:type_name -> loka.api.v1.DrainCmd
	23, // 16: loka.api.v1.LaunchSessionCmd.initial_mode:type_name -> loka.api.v1.ExecMode
	24, // 17: loka.api.v1.ExecCommandCmd.commands:type_name -> loka.api.v1.Command
	25, // 18: loka.api.v1.CreateCheckpointCmd.type:type_name -> loka.api.v1.CheckpointType
	23, // 19: loka.api.v1.SetModeCmd.mode:type_name -> loka.api.v1.ExecMode
	22, // 20: loka.api.v1.SessionStatusReport.status:type_name -> loka.api.v1.SessionStatus
	26, // 21: loka.api.v1.ExecReport.status:type_name -> loka.api.v1.ExecStatus
	27, // 22: loka.api.v1.ExecReport.results:type_name -> loka.api.v1.CommandResult
	0,  // 23: loka.api.v1.WorkerService.Register:input_type -> loka.api.v1.RegisterRequest
	4,  // 24: loka.api.v1.WorkerService.Heartbeat:input_type -> loka.api.v1.HeartbeatMessage
	14, // 25: loka.api.v1.WorkerService.ReportSessionStatus:input_type -> loka.api.v1.SessionStatusReport
	15, // 26: loka.api.v1.WorkerService.ReportCheckpointComplete:input_type -> loka.api.v1.CheckpointReport
	16, // 27: loka.api.v1.WorkerService.ReportExecComplete:input_type -> loka.api.v1.ExecReport
	1,  // 28: loka.api.v1.WorkerService.Register:output_type -> loka.api.v1.RegisterResponse
	6,  // 29: loka.api.v1.WorkerService.Heartbeat:output_type -> loka.api.v1.WorkerCommand
	28, // 30: loka.api.v1.WorkerService.ReportSessionStatus:output_type -> google.protobuf.Empty
	28, // 31: loka.api.v1.WorkerService.ReportCheckpointComplete:output_type -> google.protobuf.Empty
	28, // 32: loka.api.v1.WorkerService.ReportExecComplete:output_type -> google.protobuf.Empty
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_types_proto_init()
	file_worker_proto_msgTypes[6].OneofWrappers = []any{
		(*WorkerCommand_LaunchSession)(nil),
		(*WorkerCommand_StopSession)(nil),
		(*WorkerCommand_ExecCommand)(nil),
		(*WorkerCommand_CreateCheckpoint)(nil),
		(*WorkerCommand_RestoreCheckpoint)(nil),
		(*WorkerCommand_SetMode)(nil),
		(*WorkerCommand_Drain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
