package provider

import "fmt"

// BootstrapConfig holds the configuration needed to bootstrap a worker on a new machine.
type BootstrapConfig struct {
	ControlPlaneAddr string
	Token            string
	Provider         string
	Labels           map[string]string
	WorkerVersion    string // Version of loka-worker to install.
}

// GenerateCloudInit creates a cloud-init userdata script that installs and starts loka-worker.
func GenerateCloudInit(cfg BootstrapConfig) string {
	labelFlags := ""
	for k, v := range cfg.Labels {
		labelFlags += fmt.Sprintf("    %s: %s\n", k, v)
	}

	version := cfg.WorkerVersion
	if version == "" {
		version = "latest"
	}

	return fmt.Sprintf(`#!/bin/bash
set -euo pipefail

# LOKA Worker Bootstrap Script
# Generated by lokad for provider: %s

echo "==> Installing LOKA worker agent..."

# Install loka-worker binary
curl -fsSL https://vyprai.github.io/loka/install.sh/worker | bash -s -- --version %s

# Create configuration
mkdir -p /etc/loka
cat > /etc/loka/worker.yaml <<'WORKER_CONFIG'
control_plane:
  address: "%s"

data_dir: /var/loka/worker
provider: %s
token: "%s"

labels:
%s
tls:
  enabled: false
WORKER_CONFIG

# Create systemd service
cat > /etc/systemd/system/loka-worker.service <<'SYSTEMD'
[Unit]
Description=LOKA Worker Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/loka-worker
Environment=LOKA_WORKER_CONFIG=/etc/loka/worker.yaml
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
SYSTEMD

# Start worker
systemctl daemon-reload
systemctl enable loka-worker
systemctl start loka-worker

echo "==> LOKA worker agent started"
`, cfg.Provider, version, cfg.ControlPlaneAddr, cfg.Provider, cfg.Token, labelFlags)
}
